import { ServerResponse } from '@/model/response';
import { CatalogueItemCommand, Publisher } from '@/model/catalogue';

export enum EnumDraftStatus {
  /**
   * Asset is editable
   */
  DRAFT = 'DRAFT',
  /**
   * Asset is submitted and automated metadata is being computed
   */
  SUBMITTED = 'SUBMITTED',
  /**
   * Automated metadata has been computed and HelpDesk review is required
   */
  PENDING_HELPDESK_REVIEW = 'PENDING_HELPDESK_REVIEW',
  /**
   * HelpDesk user rejects the asset
   */
  HELPDESK_REJECTED = 'HELPDESK_REJECTED',
  /**
   * HelpDesk user accepts the asset. Provider review is required. Provider
   * may adjust the visibility of the metadata
   */
  PENDING_PROVIDER_REVIEW = 'PENDING_PROVIDER_REVIEW',
  /**
   * Provider rejects the asset
   */
  PROVIDER_REJECTED = 'PROVIDER_REJECTED',
  /**
   * Provider accepted the asset and final post-processing actions are executed
   */
  POST_PROCESSING = 'POST_PROCESSING',
  /**
   * Draft is published
   */
  PUBLISHED = 'PUBLISHED',
}

export enum EnumSortField {
  CREATED_ON = 'CREATED_ON',
  MODIFIED_ON = 'MODIFIED_ON',
  PROVIDER = 'PROVIDER',
  STATUS = 'STATUS',
  TITLE = 'TITLE',
  VERSION = 'VERSION',
}

export interface AssetDraftQuery {
  status: EnumDraftStatus[];
}


export interface AssetDraft {
  /**
   * Catalogue draft id. Always equal to key property
   */
  assetDraft: string;
  /**
   * Published asset id. The value is generated by the PID service
   */
  assetPublished: string;
  /**
   * Draft data
   */
  command: CatalogueItemCommand;
  /**
   * Creation date in ISO format
   */
  createdOn: string;
  /**
   * Rejection reason if the draft has been rejected by a HelpDesk user
   */
  helpdeskRejectionReason: string;
  /**
   * True if the file should be imported into PostGIS database and published using WMS/WFS endpoints
   */
  ingested: boolean;
  /**
   * Draft unique identifier. Also the key for the catalogue draft record.
   * If the draft is submitted and a workflow instance is initialized, it
   * is used as the business key
   */
  key: string;
  /**
   * Date of lat update in ISO format
   */
  modifiedOn: string;
  /**
   * Rejection reason if the draft has been rejected by the provider
   */
  providerRejectionReason: string;
  /**
   * Publisher details
   */
  publisher: Publisher,
  /**
   * Draft status
   */
  status: EnumDraftStatus;
  /**
   * Asset title
   */
  title: string;
  /**
   * Asset version
   */
  version: string;
}

export interface AssetDraftReviewCommand {
  reason?: string;
  rejected: boolean;
}

export type HarvestImportResponse = ServerResponse<{ [id: string]: AssetDraft }>;
