export enum EnumRole {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_USER = 'ROLE_USER',
  ROLE_PROVIDER = 'ROLE_PROVIDER',
  ROLE_CONSUMER = 'ROLE_CONSUMER',
  ROLE_DEVELOPER = 'ROLE_DEVELOPER',
  ROLE_HELPDESK = 'ROLE_HELPDESK',
  ROLE_VENDOR_USER = 'ROLE_VENDOR_USER',
  ROLE_VENDOR_PROVIDER = 'ROLE_VENDOR_PROVIDER',
  ROLE_VENDOR_CONSUMER = 'ROLE_VENDOR_CONSUMER',
  ROLE_VENDOR_ANALYTICS = 'ROLE_VENDOR_ANALYTICS',
}

export enum EnumVendorRole {
  ROLE_VENDOR_USER = 'ROLE_VENDOR_USER',
  ROLE_VENDOR_PROVIDER = 'ROLE_VENDOR_PROVIDER',
  ROLE_VENDOR_CONSUMER = 'ROLE_VENDOR_CONSUMER',
  ROLE_VENDOR_ANALYTICS = 'ROLE_VENDOR_ANALYTICS',
}
