export enum EnumRole {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_USER = 'ROLE_USER',
  ROLE_PROVIDER = 'ROLE_PROVIDER',
  ROLE_CONSUMER = 'ROLE_CONSUMER',
  ROLE_DEVELOPER = 'ROLE_DEVELOPER',
  ROLE_HELPDESK = 'ROLE_HELPDESK',
}

export default EnumRole;
