/* eslint-disable */
export default [
    {"name":"Austria","code":"AT"},
    {"name":"Belgium","code":"BE"},
    {"name":"Bulgaria","code":"BG"},
    {"name":"Croatia","code":"HR"},
    {"name":"Cyprus","code":"CY"},
    {"name":"Czechia","code":"CZ"},
    {"name":"Denmark","code":"DK"},
    {"name":"Estonia","code":"EE"},
    {"name":"Finland","code":"FI"},
    {"name":"France","code":"FR"},
    {"name":"Germany","code":"DE"},
    {"name":"Greece","code":"EL"},
    {"name":"Hungary","code":"HU"},
    {"name":"Iceland","code":"IS"},
    {"name":"Ireland","code":"IE"},
    {"name":"Italy","code":"IT"},
    {"name":"Latvia","code":"LV"},
    {"name":"Liechtenstein","code":"LI"},
    {"name":"Lithuania","code":"LT"},
    {"name":"Luxembourg","code":"LU"},
    {"name":"Malta","code":"MT"},
    {"name":"Netherlands","code":"NL"},
    {"name":"Norway","code":"NO"},
    {"name":"Poland","code":"PL"},
    {"name":"Portugal","code":"PT"},
    {"name":"Romania","code":"RO"},
    {"name":"Slovak Republic","code":"SK"},
    {"name":"Slovenia","code":"SI"},
    {"name":"Spain","code":"ES"},
    {"name":"Sweden","code":"SE"},
    {"name":"Switzerland","code":"CH"},
    {"name":"United Kingdom","code":"UK"}
];
    