/* eslint-disable */
export default [
    {"code":"DE","name":"Donau-Ries"},
    {"code":"DE","name":"Oberallgäu"},
    {"code":"DE","name":"Berlin"},
    {"code":"DE","name":"Berlin"},
    {"code":"DE","name":"Berlin"},
    {"code":"DE","name":"Brandenburg"},
    {"code":"DE","name":"Brandenburg"},
    {"code":"DE","name":"Brandenburg an der Havel, Kreisfreie Stadt"},
    {"code":"DE","name":"Cottbus, Kreisfreie Stadt"},
    {"code":"DE","name":"Frankfurt (Oder), Kreisfreie Stadt"},
    {"code":"DE","name":"Potsdam, Kreisfreie Stadt"},
    {"code":"DE","name":"Barnim"},
    {"code":"DE","name":"Dahme-Spreewald"},
    {"code":"DE","name":"Elbe-Elster"},
    {"code":"DE","name":"Havelland"},
    {"code":"DE","name":"Märkisch-Oderland"},
    {"code":"DE","name":"Oberhavel"},
    {"code":"DE","name":"Oberspreewald-Lausitz"},
    {"code":"DE","name":"Oder-Spree"},
    {"code":"DE","name":"Ostprignitz-Ruppin"},
    {"code":"DE","name":"Potsdam-Mittelmark"},
    {"code":"DE","name":"Prignitz"},
    {"code":"DE","name":"Spree-Neiße"},
    {"code":"DE","name":"Teltow-Fläming"},
    {"code":"DE","name":"Uckermark"},
    {"code":"DE","name":"Bremen"},
    {"code":"DE","name":"Bremen"},
    {"code":"DE","name":"Bremen, Kreisfreie Stadt"},
    {"code":"DE","name":"Bremerhaven, Kreisfreie Stadt"},
    {"code":"DE","name":"Hamburg"},
    {"code":"DE","name":"Hamburg"},
    {"code":"DE","name":"Hamburg"},
    {"code":"DE","name":"Hessen"},
    {"code":"DE","name":"Darmstadt"},
    {"code":"DE","name":"Darmstadt, Kreisfreie Stadt"},
    {"code":"DE","name":"Frankfurt am Main, Kreisfreie Stadt"},
    {"code":"DE","name":"Offenbach am Main, Kreisfreie Stadt"},
    {"code":"DE","name":"Wiesbaden, Kreisfreie Stadt"},
    {"code":"DE","name":"Bergstraße"},
    {"code":"DE","name":"Darmstadt-Dieburg"},
    {"code":"DE","name":"Groß-Gerau"},
    {"code":"DE","name":"Hochtaunuskreis"},
    {"code":"DE","name":"Main-Kinzig-Kreis"},
    {"code":"DE","name":"Main-Taunus-Kreis"},
    {"code":"DE","name":"Odenwaldkreis"},
    {"code":"DE","name":"Offenbach, Landkreis"},
    {"code":"DE","name":"Rheingau-Taunus-Kreis"},
    {"code":"DE","name":"Wetteraukreis"},
    {"code":"DE","name":"Gießen"},
    {"code":"DE","name":"Gießen, Landkreis"},
    {"code":"DE","name":"Lahn-Dill-Kreis"},
    {"code":"DE","name":"Limburg-Weilburg"},
    {"code":"DE","name":"Marburg-Biedenkopf"},
    {"code":"DE","name":"Vogelsbergkreis"},
    {"code":"DE","name":"Kassel"},
    {"code":"DE","name":"Kassel, Kreisfreie Stadt"},
    {"code":"DE","name":"Fulda"},
    {"code":"DE","name":"Hersfeld-Rotenburg"},
    {"code":"DE","name":"Kassel, Landkreis"},
    {"code":"DE","name":"Schwalm-Eder-Kreis"},
    {"code":"DE","name":"Waldeck-Frankenberg"},
    {"code":"DE","name":"Werra-Meißner-Kreis"},
    {"code":"DE","name":"Mecklenburg-Vorpommern"},
    {"code":"DE","name":"Mecklenburg-Vorpommern"},
    {"code":"DE","name":"Rostock, Kreisfreie Stadt"},
    {"code":"DE","name":"Schwerin, Kreisfreie Stadt"},
    {"code":"DE","name":"Mecklenburgische Seenplatte"},
    {"code":"DE","name":"Landkreis Rostock"},
    {"code":"DE","name":"Vorpommern-Rügen"},
    {"code":"DE","name":"Nordwestmecklenburg"},
    {"code":"DE","name":"Vorpommern-Greifswald"},
    {"code":"DE","name":"Ludwigslust-Parchim"},
    {"code":"DE","name":"Niedersachsen"},
    {"code":"DE","name":"Braunschweig"},
    {"code":"DE","name":"Braunschweig, Kreisfreie Stadt"},
    {"code":"DE","name":"Salzgitter, Kreisfreie Stadt"},
    {"code":"DE","name":"Wolfsburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Gifhorn"},
    {"code":"DE","name":"Goslar"},
    {"code":"DE","name":"Helmstedt"},
    {"code":"DE","name":"Northeim"},
    {"code":"DE","name":"Peine"},
    {"code":"DE","name":"Wolfenbüttel"},
    {"code":"DE","name":"Göttingen"},
    {"code":"DE","name":"Hannover"},
    {"code":"DE","name":"Diepholz"},
    {"code":"DE","name":"Hameln-Pyrmont"},
    {"code":"DE","name":"Hildesheim"},
    {"code":"DE","name":"Holzminden"},
    {"code":"DE","name":"Nienburg (Weser)"},
    {"code":"DE","name":"Schaumburg"},
    {"code":"DE","name":"Region Hannover"},
    {"code":"DE","name":"Lüneburg"},
    {"code":"DE","name":"Celle"},
    {"code":"DE","name":"Cuxhaven"},
    {"code":"DE","name":"Harburg"},
    {"code":"DE","name":"Lüchow-Dannenberg"},
    {"code":"DE","name":"Lüneburg, Landkreis"},
    {"code":"DE","name":"Osterholz"},
    {"code":"DE","name":"Rotenburg (Wümme)"},
    {"code":"DE","name":"Heidekreis"},
    {"code":"DE","name":"Stade"},
    {"code":"DE","name":"Uelzen"},
    {"code":"DE","name":"Verden"},
    {"code":"DE","name":"Weser-Ems"},
    {"code":"DE","name":"Delmenhorst, Kreisfreie Stadt"},
    {"code":"DE","name":"Emden, Kreisfreie Stadt"},
    {"code":"DE","name":"Oldenburg (Oldenburg), Kreisfreie Stadt"},
    {"code":"DE","name":"Osnabrück, Kreisfreie Stadt"},
    {"code":"DE","name":"Wilhelmshaven, Kreisfreie Stadt"},
    {"code":"DE","name":"Ammerland"},
    {"code":"DE","name":"Aurich"},
    {"code":"DE","name":"Cloppenburg"},
    {"code":"DE","name":"Emsland"},
    {"code":"DE","name":"Friesland (DE)"},
    {"code":"DE","name":"Grafschaft Bentheim"},
    {"code":"DE","name":"Leer"},
    {"code":"DE","name":"Oldenburg, Landkreis"},
    {"code":"DE","name":"Osnabrück, Landkreis"},
    {"code":"DE","name":"Vechta"},
    {"code":"DE","name":"Wesermarsch"},
    {"code":"DE","name":"Wittmund"},
    {"code":"DE","name":"Nordrhein-Westfalen"},
    {"code":"DE","name":"Düsseldorf"},
    {"code":"DE","name":"Düsseldorf, Kreisfreie Stadt"},
    {"code":"DE","name":"Duisburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Essen, Kreisfreie Stadt"},
    {"code":"DE","name":"Krefeld, Kreisfreie Stadt"},
    {"code":"DE","name":"Mönchengladbach, Kreisfreie Stadt"},
    {"code":"DE","name":"Mülheim an der Ruhr, Kreisfreie Stadt"},
    {"code":"DE","name":"Oberhausen, Kreisfreie Stadt"},
    {"code":"DE","name":"Remscheid, Kreisfreie Stadt"},
    {"code":"DE","name":"Solingen, Kreisfreie Stadt"},
    {"code":"DE","name":"Wuppertal, Kreisfreie Stadt"},
    {"code":"DE","name":"Kleve"},
    {"code":"DE","name":"Mettmann"},
    {"code":"DE","name":"Rhein-Kreis Neuss"},
    {"code":"DE","name":"Viersen"},
    {"code":"DE","name":"Wesel"},
    {"code":"DE","name":"Köln"},
    {"code":"DE","name":"Bonn, Kreisfreie Stadt"},
    {"code":"DE","name":"Köln, Kreisfreie Stadt"},
    {"code":"DE","name":"Leverkusen, Kreisfreie Stadt"},
    {"code":"DE","name":"Düren"},
    {"code":"DE","name":"Rhein-Erft-Kreis"},
    {"code":"DE","name":"Euskirchen"},
    {"code":"DE","name":"Heinsberg"},
    {"code":"DE","name":"Oberbergischer Kreis"},
    {"code":"DE","name":"Rheinisch-Bergischer Kreis"},
    {"code":"DE","name":"Rhein-Sieg-Kreis"},
    {"code":"DE","name":"Städteregion Aachen"},
    {"code":"DE","name":"Münster"},
    {"code":"DE","name":"Bottrop, Kreisfreie Stadt"},
    {"code":"DE","name":"Gelsenkirchen, Kreisfreie Stadt"},
    {"code":"DE","name":"Münster, Kreisfreie Stadt"},
    {"code":"DE","name":"Borken"},
    {"code":"DE","name":"Coesfeld"},
    {"code":"DE","name":"Recklinghausen"},
    {"code":"DE","name":"Steinfurt"},
    {"code":"DE","name":"Warendorf"},
    {"code":"DE","name":"Detmold"},
    {"code":"DE","name":"Bielefeld, Kreisfreie Stadt"},
    {"code":"DE","name":"Gütersloh"},
    {"code":"DE","name":"Herford"},
    {"code":"DE","name":"Höxter"},
    {"code":"DE","name":"Lippe"},
    {"code":"DE","name":"Minden-Lübbecke"},
    {"code":"DE","name":"Paderborn"},
    {"code":"DE","name":"Arnsberg"},
    {"code":"DE","name":"Bochum, Kreisfreie Stadt"},
    {"code":"DE","name":"Dortmund, Kreisfreie Stadt"},
    {"code":"DE","name":"Hagen, Kreisfreie Stadt"},
    {"code":"DE","name":"Hamm, Kreisfreie Stadt"},
    {"code":"DE","name":"Herne, Kreisfreie Stadt"},
    {"code":"DE","name":"Ennepe-Ruhr-Kreis"},
    {"code":"DE","name":"Hochsauerlandkreis"},
    {"code":"DE","name":"Märkischer Kreis"},
    {"code":"DE","name":"Olpe"},
    {"code":"DE","name":"Siegen-Wittgenstein"},
    {"code":"DE","name":"Soest"},
    {"code":"DE","name":"Unna"},
    {"code":"DE","name":"Rheinland-Pfalz"},
    {"code":"DE","name":"Koblenz"},
    {"code":"DE","name":"Koblenz, Kreisfreie Stadt"},
    {"code":"DE","name":"Ahrweiler"},
    {"code":"DE","name":"Altenkirchen (Westerwald)"},
    {"code":"DE","name":"Bad Kreuznach"},
    {"code":"DE","name":"Birkenfeld"},
    {"code":"DE","name":"Mayen-Koblenz"},
    {"code":"DE","name":"Neuwied"},
    {"code":"DE","name":"Rhein-Lahn-Kreis"},
    {"code":"DE","name":"Westerwaldkreis"},
    {"code":"DE","name":"Cochem-Zell"},
    {"code":"DE","name":"Rhein-Hunsrück-Kreis"},
    {"code":"DE","name":"Trier"},
    {"code":"DE","name":"Trier, Kreisfreie Stadt"},
    {"code":"DE","name":"Bernkastel-Wittlich"},
    {"code":"DE","name":"Eifelkreis Bitburg-Prüm"},
    {"code":"DE","name":"Vulkaneifel"},
    {"code":"DE","name":"Trier-Saarburg"},
    {"code":"DE","name":"Rheinhessen-Pfalz"},
    {"code":"DE","name":"Frankenthal (Pfalz), Kreisfreie Stadt"},
    {"code":"DE","name":"Kaiserslautern, Kreisfreie Stadt"},
    {"code":"DE","name":"Landau in der Pfalz, Kreisfreie Stadt"},
    {"code":"DE","name":"Ludwigshafen am Rhein, Kreisfreie Stadt"},
    {"code":"DE","name":"Mainz, Kreisfreie Stadt"},
    {"code":"DE","name":"Neustadt an der Weinstraße, Kreisfreie Stadt"},
    {"code":"DE","name":"Pirmasens, Kreisfreie Stadt"},
    {"code":"DE","name":"Speyer, Kreisfreie Stadt"},
    {"code":"DE","name":"Worms, Kreisfreie Stadt"},
    {"code":"DE","name":"Zweibrücken, Kreisfreie Stadt"},
    {"code":"DE","name":"Alzey-Worms"},
    {"code":"DE","name":"Bad Dürkheim"},
    {"code":"DE","name":"Donnersbergkreis"},
    {"code":"DE","name":"Germersheim"},
    {"code":"DE","name":"Kaiserslautern, Landkreis"},
    {"code":"DE","name":"Kusel"},
    {"code":"DE","name":"Südliche Weinstraße"},
    {"code":"DE","name":"Rhein-Pfalz-Kreis"},
    {"code":"DE","name":"Mainz-Bingen"},
    {"code":"DE","name":"Südwestpfalz"},
    {"code":"DE","name":"Saarland"},
    {"code":"DE","name":"Saarland"},
    {"code":"DE","name":"Regionalverband Saarbrücken"},
    {"code":"DE","name":"Merzig-Wadern"},
    {"code":"DE","name":"Neunkirchen"},
    {"code":"DE","name":"Saarlouis"},
    {"code":"DE","name":"Saarpfalz-Kreis"},
    {"code":"DE","name":"St. Wendel"},
    {"code":"DE","name":"Sachsen"},
    {"code":"DE","name":"Dresden"},
    {"code":"AL","name":"Shqipëria"},
    {"code":"AL","name":"Shqipëria"},
    {"code":"AL","name":"Veri"},
    {"code":"AL","name":"Dibër"},
    {"code":"AL","name":"Durrës"},
    {"code":"AL","name":"Kukës"},
    {"code":"AL","name":"Lezhë"},
    {"code":"AL","name":"Shkodër"},
    {"code":"AL","name":"Qender"},
    {"code":"AL","name":"Elbasan"},
    {"code":"AL","name":"Tiranë"},
    {"code":"AL","name":"Jug"},
    {"code":"AL","name":"Berat"},
    {"code":"AL","name":"Fier"},
    {"code":"AL","name":"Gjirokastër"},
    {"code":"AL","name":"Korcë"},
    {"code":"AL","name":"Vlorë"},
    {"code":"AT","name":"Österreich"},
    {"code":"AT","name":"Ostösterreich"},
    {"code":"AT","name":"Burgenland"},
    {"code":"AT","name":"Mittelburgenland"},
    {"code":"AT","name":"Nordburgenland"},
    {"code":"AT","name":"Südburgenland"},
    {"code":"AT","name":"Niederösterreich"},
    {"code":"AT","name":"Mostviertel-Eisenwurzen"},
    {"code":"AT","name":"Niederösterreich-Süd"},
    {"code":"AT","name":"Sankt Pölten"},
    {"code":"AT","name":"Waldviertel"},
    {"code":"AT","name":"Weinviertel"},
    {"code":"AT","name":"Wiener Umland/Nordteil"},
    {"code":"AT","name":"Wiener Umland/Südteil"},
    {"code":"AT","name":"Wien"},
    {"code":"AT","name":"Wien"},
    {"code":"AT","name":"Südösterreich"},
    {"code":"AT","name":"Kärnten"},
    {"code":"AT","name":"Klagenfurt-Villach"},
    {"code":"AT","name":"Oberkärnten"},
    {"code":"AT","name":"Unterkärnten"},
    {"code":"AT","name":"Steiermark"},
    {"code":"AT","name":"Graz"},
    {"code":"AT","name":"Liezen"},
    {"code":"AT","name":"Östliche Obersteiermark"},
    {"code":"AT","name":"Oststeiermark"},
    {"code":"AT","name":"West- und Südsteiermark"},
    {"code":"AT","name":"Westliche Obersteiermark"},
    {"code":"AT","name":"Westösterreich"},
    {"code":"AT","name":"Oberösterreich"},
    {"code":"AT","name":"Innviertel"},
    {"code":"AT","name":"Linz-Wels"},
    {"code":"AT","name":"Mühlviertel"},
    {"code":"AT","name":"Steyr-Kirchdorf"},
    {"code":"AT","name":"Traunviertel"},
    {"code":"AT","name":"Salzburg"},
    {"code":"AT","name":"Lungau"},
    {"code":"AT","name":"Pinzgau-Pongau"},
    {"code":"AT","name":"Salzburg und Umgebung"},
    {"code":"AT","name":"Tirol"},
    {"code":"AT","name":"Außerfern"},
    {"code":"AT","name":"Innsbruck"},
    {"code":"AT","name":"Osttirol"},
    {"code":"AT","name":"Tiroler Oberland"},
    {"code":"AT","name":"Tiroler Unterland"},
    {"code":"AT","name":"Vorarlberg"},
    {"code":"AT","name":"Bludenz-Bregenzer Wald"},
    {"code":"AT","name":"Rheintal-Bodenseegebiet"},
    {"code":"BE","name":"Belgique/België"},
    {"code":"BE","name":"Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest"},
    {"code":"BE","name":"Région de Bruxelles-Capitale/ Brussels Hoofdstedelijk Gewest"},
    {"code":"BE","name":"Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad"},
    {"code":"BE","name":"Vlaams Gewest"},
    {"code":"BE","name":"Prov. Antwerpen"},
    {"code":"BE","name":"Arr. Antwerpen"},
    {"code":"BE","name":"Arr. Mechelen"},
    {"code":"BE","name":"Arr. Turnhout"},
    {"code":"BE","name":"Prov. Limburg (BE)"},
    {"code":"BE","name":"Arr. Tongeren"},
    {"code":"BE","name":"Arr. Hasselt"},
    {"code":"BE","name":"Arr. Maaseik"},
    {"code":"BE","name":"Prov. Oost-Vlaanderen"},
    {"code":"BE","name":"Arr. Aalst"},
    {"code":"BE","name":"Arr. Dendermonde"},
    {"code":"BE","name":"Arr. Eeklo"},
    {"code":"BE","name":"Arr. Gent"},
    {"code":"BE","name":"Arr. Oudenaarde"},
    {"code":"BE","name":"Arr. Sint-Niklaas"},
    {"code":"BE","name":"Prov. Vlaams-Brabant"},
    {"code":"BE","name":"Arr. Halle-Vilvoorde"},
    {"code":"BE","name":"Arr. Leuven"},
    {"code":"BE","name":"Prov. West-Vlaanderen"},
    {"code":"BE","name":"Arr. Brugge"},
    {"code":"BE","name":"Arr. Diksmuide"},
    {"code":"BE","name":"Arr. Ieper"},
    {"code":"BE","name":"Arr. Kortrijk"},
    {"code":"BE","name":"Arr. Oostende"},
    {"code":"BE","name":"Arr. Roeselare"},
    {"code":"BE","name":"Arr. Tielt"},
    {"code":"BE","name":"Arr. Veurne"},
    {"code":"BE","name":"Région wallonne"},
    {"code":"BE","name":"Prov. Brabant Wallon"},
    {"code":"BE","name":"Arr. Nivelles"},
    {"code":"BE","name":"Prov. Hainaut"},
    {"code":"BE","name":"Arr. Mons"},
    {"code":"BE","name":"Arr. Tournai-Mouscron"},
    {"code":"BE","name":"Arr. La Louvière"},
    {"code":"BE","name":"Arr. Ath"},
    {"code":"BE","name":"Arr. Charleroi"},
    {"code":"BE","name":"Arr. Soignies"},
    {"code":"BE","name":"Arr. Thuin"},
    {"code":"BE","name":"Prov. Liège"},
    {"code":"BE","name":"Arr. Huy"},
    {"code":"BE","name":"Arr. Liège"},
    {"code":"BE","name":"Arr. Waremme"},
    {"code":"BE","name":"Arr. Verviers — communes francophones"},
    {"code":"BE","name":"Bezirk Verviers — Deutschsprachige Gemeinschaft"},
    {"code":"BE","name":"Prov. Luxembourg (BE)"},
    {"code":"BE","name":"Arr. Arlon"},
    {"code":"BE","name":"Arr. Bastogne"},
    {"code":"BE","name":"Arr. Marche-en-Famenne"},
    {"code":"BE","name":"Arr. Neufchâteau"},
    {"code":"BE","name":"Arr. Virton"},
    {"code":"BE","name":"Prov. Namur"},
    {"code":"BE","name":"Arr. Dinant"},
    {"code":"BE","name":"Arr. Namur"},
    {"code":"BE","name":"Arr. Philippeville"},
    {"code":"BG","name":"Bulgaria"},
    {"code":"BG","name":"Severna i Yugoiztochna Bulgaria"},
    {"code":"BG","name":"Severozapaden"},
    {"code":"BG","name":"Vidin"},
    {"code":"BG","name":"Montana"},
    {"code":"BG","name":"Vratsa"},
    {"code":"BG","name":"Pleven"},
    {"code":"BG","name":"Lovech"},
    {"code":"BG","name":"Severen tsentralen"},
    {"code":"BG","name":"Veliko Tarnovo"},
    {"code":"BG","name":"Gabrovo"},
    {"code":"BG","name":"Ruse"},
    {"code":"BG","name":"Razgrad"},
    {"code":"BG","name":"Silistra"},
    {"code":"BG","name":"Severoiztochen"},
    {"code":"BG","name":"Varna"},
    {"code":"BG","name":"Dobrich"},
    {"code":"BG","name":"Shumen"},
    {"code":"BG","name":"Targovishte"},
    {"code":"BG","name":"Yugoiztochen"},
    {"code":"BG","name":"Burgas"},
    {"code":"BG","name":"Sliven"},
    {"code":"BG","name":"Yambol"},
    {"code":"BG","name":"Stara Zagora"},
    {"code":"BG","name":"Yugozapadna i Yuzhna tsentralna Bulgaria"},
    {"code":"BG","name":"Yugozapaden"},
    {"code":"BG","name":"Sofia (stolitsa)"},
    {"code":"BG","name":"Sofia"},
    {"code":"BG","name":"Blagoevgrad"},
    {"code":"BG","name":"Pernik"},
    {"code":"BG","name":"Kyustendil"},
    {"code":"BG","name":"Yuzhen tsentralen"},
    {"code":"BG","name":"Plovdiv"},
    {"code":"BG","name":"Haskovo"},
    {"code":"BG","name":"Pazardzhik"},
    {"code":"BG","name":"Smolyan"},
    {"code":"BG","name":"Kardzhali"},
    {"code":"CH","name":"Schweiz/Suisse/Svizzera"},
    {"code":"CH","name":"Schweiz/Suisse/Svizzera"},
    {"code":"CH","name":"Région lémanique"},
    {"code":"CH","name":"Vaud"},
    {"code":"CH","name":"Valais"},
    {"code":"CH","name":"Genève"},
    {"code":"CH","name":"Espace Mittelland"},
    {"code":"CH","name":"Bern"},
    {"code":"CH","name":"Freiburg"},
    {"code":"CH","name":"Solothurn"},
    {"code":"CH","name":"Neuchâtel"},
    {"code":"CH","name":"Jura"},
    {"code":"CH","name":"Nordwestschweiz"},
    {"code":"CH","name":"Basel-Stadt"},
    {"code":"CH","name":"Basel-Landschaft"},
    {"code":"CH","name":"Aargau"},
    {"code":"CH","name":"Zürich"},
    {"code":"CH","name":"Zürich"},
    {"code":"CH","name":"Ostschweiz"},
    {"code":"CH","name":"Glarus"},
    {"code":"CH","name":"Schaffhausen"},
    {"code":"CH","name":"Appenzell Ausserrhoden"},
    {"code":"CH","name":"Appenzell Innerrhoden"},
    {"code":"CH","name":"St. Gallen"},
    {"code":"CH","name":"Graubünden"},
    {"code":"CH","name":"Thurgau"},
    {"code":"CH","name":"Zentralschweiz"},
    {"code":"CH","name":"Luzern"},
    {"code":"CH","name":"Uri"},
    {"code":"CH","name":"Schwyz"},
    {"code":"CH","name":"Obwalden"},
    {"code":"CH","name":"Nidwalden"},
    {"code":"CH","name":"Zug"},
    {"code":"CH","name":"Ticino"},
    {"code":"CH","name":"Ticino"},
    {"code":"CY","name":"Kýpros"},
    {"code":"CY","name":"Kýpros"},
    {"code":"CY","name":"Kýpros"},
    {"code":"CY","name":"Kýpros"},
    {"code":"CZ","name":"Česko"},
    {"code":"CZ","name":"Česko"},
    {"code":"CZ","name":"Praha"},
    {"code":"CZ","name":"Hlavní město Praha"},
    {"code":"CZ","name":"Střední Čechy"},
    {"code":"CZ","name":"Středočeský kraj"},
    {"code":"CZ","name":"Jihozápad"},
    {"code":"CZ","name":"Jihočeský kraj"},
    {"code":"CZ","name":"Plzeňský kraj"},
    {"code":"CZ","name":"Severozápad"},
    {"code":"CZ","name":"Karlovarský kraj"},
    {"code":"CZ","name":"Ústecký kraj"},
    {"code":"CZ","name":"Severovýchod"},
    {"code":"CZ","name":"Liberecký kraj"},
    {"code":"CZ","name":"Královéhradecký kraj"},
    {"code":"CZ","name":"Pardubický kraj"},
    {"code":"CZ","name":"Jihovýchod"},
    {"code":"CZ","name":"Kraj Vysočina"},
    {"code":"CZ","name":"Jihomoravský kraj"},
    {"code":"CZ","name":"Střední Morava"},
    {"code":"CZ","name":"Olomoucký kraj"},
    {"code":"CZ","name":"Zlínský kraj"},
    {"code":"CZ","name":"Moravskoslezsko"},
    {"code":"CZ","name":"Moravskoslezský kraj"},
    {"code":"DE","name":"Deutschland"},
    {"code":"DE","name":"Baden-Württemberg"},
    {"code":"DE","name":"Stuttgart"},
    {"code":"DE","name":"Stuttgart, Stadtkreis"},
    {"code":"DE","name":"Böblingen"},
    {"code":"DE","name":"Esslingen"},
    {"code":"DE","name":"Göppingen"},
    {"code":"DE","name":"Ludwigsburg"},
    {"code":"DE","name":"Rems-Murr-Kreis"},
    {"code":"DE","name":"Heilbronn, Stadtkreis"},
    {"code":"DE","name":"Heilbronn, Landkreis"},
    {"code":"DE","name":"Hohenlohekreis"},
    {"code":"DE","name":"Schwäbisch Hall"},
    {"code":"DE","name":"Main-Tauber-Kreis"},
    {"code":"DE","name":"Heidenheim"},
    {"code":"DE","name":"Ostalbkreis"},
    {"code":"DE","name":"Karlsruhe"},
    {"code":"DE","name":"Baden-Baden, Stadtkreis"},
    {"code":"DE","name":"Karlsruhe, Stadtkreis"},
    {"code":"DE","name":"Karlsruhe, Landkreis"},
    {"code":"DE","name":"Rastatt"},
    {"code":"DE","name":"Heidelberg, Stadtkreis"},
    {"code":"DE","name":"Mannheim, Stadtkreis"},
    {"code":"DE","name":"Neckar-Odenwald-Kreis"},
    {"code":"DE","name":"Rhein-Neckar-Kreis"},
    {"code":"DE","name":"Pforzheim, Stadtkreis"},
    {"code":"DE","name":"Calw"},
    {"code":"DE","name":"Enzkreis"},
    {"code":"DE","name":"Freudenstadt"},
    {"code":"DE","name":"Freiburg"},
    {"code":"DE","name":"Freiburg im Breisgau, Stadtkreis"},
    {"code":"DE","name":"Breisgau-Hochschwarzwald"},
    {"code":"DE","name":"Emmendingen"},
    {"code":"DE","name":"Ortenaukreis"},
    {"code":"DE","name":"Rottweil"},
    {"code":"DE","name":"Schwarzwald-Baar-Kreis"},
    {"code":"DE","name":"Tuttlingen"},
    {"code":"DE","name":"Konstanz"},
    {"code":"DE","name":"Lörrach"},
    {"code":"DE","name":"Waldshut"},
    {"code":"DE","name":"Tübingen"},
    {"code":"DE","name":"Reutlingen"},
    {"code":"DE","name":"Tübingen, Landkreis"},
    {"code":"DE","name":"Zollernalbkreis"},
    {"code":"DE","name":"Ulm, Stadtkreis"},
    {"code":"DE","name":"Alb-Donau-Kreis"},
    {"code":"DE","name":"Biberach"},
    {"code":"DE","name":"Bodenseekreis"},
    {"code":"DE","name":"Ravensburg"},
    {"code":"DE","name":"Sigmaringen"},
    {"code":"DE","name":"Bayern"},
    {"code":"DE","name":"Oberbayern"},
    {"code":"DE","name":"Ingolstadt, Kreisfreie Stadt"},
    {"code":"DE","name":"München, Kreisfreie Stadt"},
    {"code":"DE","name":"Rosenheim, Kreisfreie Stadt"},
    {"code":"DE","name":"Altötting"},
    {"code":"DE","name":"Berchtesgadener Land"},
    {"code":"DE","name":"Bad Tölz-Wolfratshausen"},
    {"code":"DE","name":"Dachau"},
    {"code":"DE","name":"Ebersberg"},
    {"code":"DE","name":"Eichstätt"},
    {"code":"DE","name":"Erding"},
    {"code":"DE","name":"Freising"},
    {"code":"DE","name":"Fürstenfeldbruck"},
    {"code":"DE","name":"Garmisch-Partenkirchen"},
    {"code":"DE","name":"Landsberg am Lech"},
    {"code":"DE","name":"Miesbach"},
    {"code":"DE","name":"Mühldorf a. Inn"},
    {"code":"DE","name":"München, Landkreis"},
    {"code":"DE","name":"Neuburg-Schrobenhausen"},
    {"code":"DE","name":"Pfaffenhofen a. d. Ilm"},
    {"code":"DE","name":"Rosenheim, Landkreis"},
    {"code":"DE","name":"Starnberg"},
    {"code":"DE","name":"Traunstein"},
    {"code":"DE","name":"Weilheim-Schongau"},
    {"code":"DE","name":"Niederbayern"},
    {"code":"DE","name":"Landshut, Kreisfreie Stadt"},
    {"code":"DE","name":"Passau, Kreisfreie Stadt"},
    {"code":"DE","name":"Straubing, Kreisfreie Stadt"},
    {"code":"DE","name":"Deggendorf"},
    {"code":"DE","name":"Freyung-Grafenau"},
    {"code":"DE","name":"Kelheim"},
    {"code":"DE","name":"Landshut, Landkreis"},
    {"code":"DE","name":"Passau, Landkreis"},
    {"code":"DE","name":"Regen"},
    {"code":"DE","name":"Rottal-Inn"},
    {"code":"DE","name":"Straubing-Bogen"},
    {"code":"DE","name":"Dingolfing-Landau"},
    {"code":"DE","name":"Oberpfalz"},
    {"code":"DE","name":"Amberg, Kreisfreie Stadt"},
    {"code":"DE","name":"Regensburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Weiden i. d. Opf, Kreisfreie Stadt"},
    {"code":"DE","name":"Amberg-Sulzbach"},
    {"code":"DE","name":"Cham"},
    {"code":"DE","name":"Neumarkt i. d. OPf."},
    {"code":"DE","name":"Neustadt a. d. Waldnaab"},
    {"code":"DE","name":"Regensburg, Landkreis"},
    {"code":"DE","name":"Schwandorf"},
    {"code":"DE","name":"Tirschenreuth"},
    {"code":"DE","name":"Oberfranken"},
    {"code":"DE","name":"Bamberg, Kreisfreie Stadt"},
    {"code":"DE","name":"Bayreuth, Kreisfreie Stadt"},
    {"code":"DE","name":"Coburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Hof, Kreisfreie Stadt"},
    {"code":"DE","name":"Bamberg, Landkreis"},
    {"code":"DE","name":"Bayreuth, Landkreis"},
    {"code":"DE","name":"Coburg, Landkreis"},
    {"code":"DE","name":"Forchheim"},
    {"code":"DE","name":"Hof, Landkreis"},
    {"code":"DE","name":"Kronach"},
    {"code":"DE","name":"Kulmbach"},
    {"code":"DE","name":"Lichtenfels"},
    {"code":"DE","name":"Wunsiedel i. Fichtelgebirge"},
    {"code":"DE","name":"Mittelfranken"},
    {"code":"DE","name":"Ansbach, Kreisfreie Stadt"},
    {"code":"DE","name":"Erlangen, Kreisfreie Stadt"},
    {"code":"DE","name":"Fürth, Kreisfreie Stadt"},
    {"code":"DE","name":"Nürnberg, Kreisfreie Stadt"},
    {"code":"DE","name":"Schwabach, Kreisfreie Stadt"},
    {"code":"DE","name":"Ansbach, Landkreis"},
    {"code":"DE","name":"Erlangen-Höchstadt"},
    {"code":"DE","name":"Fürth, Landkreis"},
    {"code":"DE","name":"Nürnberger Land"},
    {"code":"DE","name":"Neustadt a. d. Aisch-Bad Windsheim"},
    {"code":"DE","name":"Roth"},
    {"code":"DE","name":"Weißenburg-Gunzenhausen"},
    {"code":"DE","name":"Unterfranken"},
    {"code":"DE","name":"Aschaffenburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Schweinfurt, Kreisfreie Stadt"},
    {"code":"DE","name":"Würzburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Aschaffenburg, Landkreis"},
    {"code":"DE","name":"Bad Kissingen"},
    {"code":"DE","name":"Rhön-Grabfeld"},
    {"code":"DE","name":"Haßberge"},
    {"code":"DE","name":"Kitzingen"},
    {"code":"DE","name":"Miltenberg"},
    {"code":"DE","name":"Main-Spessart"},
    {"code":"DE","name":"Schweinfurt, Landkreis"},
    {"code":"DE","name":"Würzburg, Landkreis"},
    {"code":"DE","name":"Schwaben"},
    {"code":"DE","name":"Augsburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Kaufbeuren, Kreisfreie Stadt"},
    {"code":"DE","name":"Kempten (Allgäu), Kreisfreie Stadt"},
    {"code":"DE","name":"Memmingen, Kreisfreie Stadt"},
    {"code":"DE","name":"Aichach-Friedberg"},
    {"code":"DE","name":"Augsburg, Landkreis"},
    {"code":"DE","name":"Dillingen a.d. Donau"},
    {"code":"DE","name":"Günzburg"},
    {"code":"DE","name":"Neu-Ulm"},
    {"code":"DE","name":"Lindau (Bodensee)"},
    {"code":"DE","name":"Ostallgäu"},
    {"code":"DE","name":"Unterallgäu"},
    {"code":"RS","name":"Region Južne i Istočne Srbije"},
    {"code":"RS","name":"Borska oblast"},
    {"code":"RS","name":"Braničevska oblast"},
    {"code":"RS","name":"Zaječarska oblast"},
    {"code":"RS","name":"Jablanička oblast"},
    {"code":"RS","name":"Nišavska oblast"},
    {"code":"RS","name":"Pirotska oblast"},
    {"code":"RS","name":"Podunavska oblast"},
    {"code":"RS","name":"Pčinjska oblast"},
    {"code":"RS","name":"Toplička oblast"},
    {"code":"SE","name":"Sverige"},
    {"code":"SE","name":"Östra Sverige"},
    {"code":"SE","name":"Stockholm"},
    {"code":"SE","name":"Stockholms län"},
    {"code":"SE","name":"Östra Mellansverige"},
    {"code":"SE","name":"Uppsala län"},
    {"code":"SE","name":"Södermanlands län"},
    {"code":"SE","name":"Östergötlands län"},
    {"code":"SE","name":"Örebro län"},
    {"code":"SE","name":"Västmanlands län"},
    {"code":"SE","name":"Södra Sverige"},
    {"code":"SE","name":"Småland med öarna"},
    {"code":"SE","name":"Jönköpings län"},
    {"code":"SE","name":"Kronobergs län"},
    {"code":"SE","name":"Kalmar län"},
    {"code":"SE","name":"Gotlands län"},
    {"code":"SE","name":"Sydsverige"},
    {"code":"SE","name":"Blekinge län"},
    {"code":"SE","name":"Skåne län"},
    {"code":"SE","name":"Västsverige"},
    {"code":"SE","name":"Hallands län"},
    {"code":"SE","name":"Västra Götalands län"},
    {"code":"SE","name":"Norra Sverige"},
    {"code":"SE","name":"Norra Mellansverige"},
    {"code":"SE","name":"Värmlands län"},
    {"code":"SE","name":"Dalarnas län"},
    {"code":"SE","name":"Gävleborgs län"},
    {"code":"SE","name":"Mellersta Norrland"},
    {"code":"SE","name":"Västernorrlands län"},
    {"code":"SE","name":"Jämtlands län"},
    {"code":"SE","name":"Övre Norrland"},
    {"code":"SE","name":"Västerbottens län"},
    {"code":"SE","name":"Norrbottens län"},
    {"code":"SI","name":"Slovenija"},
    {"code":"SI","name":"Slovenija"},
    {"code":"SI","name":"Vzhodna Slovenija"},
    {"code":"SI","name":"Pomurska"},
    {"code":"SI","name":"Podravska"},
    {"code":"SI","name":"Koroška"},
    {"code":"SI","name":"Savinjska"},
    {"code":"SI","name":"Zasavska"},
    {"code":"SI","name":"Posavska"},
    {"code":"SI","name":"Jugovzhodna Slovenija"},
    {"code":"SI","name":"Primorsko-notranjska"},
    {"code":"SI","name":"Zahodna Slovenija"},
    {"code":"SI","name":"Osrednjeslovenska"},
    {"code":"SI","name":"Gorenjska"},
    {"code":"SI","name":"Goriška"},
    {"code":"SI","name":"Obalno-kraška"},
    {"code":"SK","name":"Slovensko"},
    {"code":"SK","name":"Slovensko"},
    {"code":"SK","name":"Bratislavský kraj"},
    {"code":"SK","name":"Bratislavský kraj"},
    {"code":"SK","name":"Západné Slovensko"},
    {"code":"SK","name":"Trnavský kraj"},
    {"code":"SK","name":"Trenčiansky kraj"},
    {"code":"SK","name":"Nitriansky kraj"},
    {"code":"SK","name":"Stredné Slovensko"},
    {"code":"SK","name":"Žilinský kraj"},
    {"code":"SK","name":"Banskobystrický kraj"},
    {"code":"SK","name":"Východné Slovensko"},
    {"code":"SK","name":"Prešovský kraj"},
    {"code":"SK","name":"Košický kraj"},
    {"code":"TR","name":"Türkiye"},
    {"code":"TR","name":"İstanbul"},
    {"code":"TR","name":"İstanbul"},
    {"code":"TR","name":"İstanbul"},
    {"code":"TR","name":"Batı Marmara"},
    {"code":"TR","name":"Tekirdağ, Edirne, Kırklareli"},
    {"code":"TR","name":"Tekirdağ"},
    {"code":"TR","name":"Edirne"},
    {"code":"TR","name":"Kırklareli"},
    {"code":"TR","name":"Balıkesir, Çanakkale"},
    {"code":"TR","name":"Balıkesir"},
    {"code":"TR","name":"Çanakkale"},
    {"code":"TR","name":"Ege"},
    {"code":"TR","name":"İzmir"},
    {"code":"TR","name":"İzmir"},
    {"code":"TR","name":"Aydın, Denizli, Muğla"},
    {"code":"TR","name":"Aydın"},
    {"code":"TR","name":"Denizli"},
    {"code":"TR","name":"Muğla"},
    {"code":"TR","name":"Manisa, Afyonkarahisar, Kütahya, Uşak"},
    {"code":"TR","name":"Manisa"},
    {"code":"TR","name":"Afyonkarahisar"},
    {"code":"TR","name":"Kütahya"},
    {"code":"TR","name":"Uşak"},
    {"code":"TR","name":"Doğu Marmara"},
    {"code":"TR","name":"Bursa, Eskişehir, Bilecik"},
    {"code":"TR","name":"Bursa"},
    {"code":"TR","name":"Eskişehir"},
    {"code":"TR","name":"Bilecik"},
    {"code":"TR","name":"Kocaeli, Sakarya, Düzce, Bolu, Yalova"},
    {"code":"TR","name":"Kocaeli"},
    {"code":"TR","name":"Sakarya"},
    {"code":"TR","name":"Düzce"},
    {"code":"TR","name":"Bolu"},
    {"code":"TR","name":"Yalova"},
    {"code":"TR","name":"Batı Anadolu"},
    {"code":"TR","name":"Ankara"},
    {"code":"TR","name":"Ankara"},
    {"code":"TR","name":"Konya, Karaman"},
    {"code":"TR","name":"Konya"},
    {"code":"TR","name":"Karaman"},
    {"code":"TR","name":"Akdeniz"},
    {"code":"TR","name":"Antalya, Isparta, Burdur"},
    {"code":"TR","name":"Antalya"},
    {"code":"TR","name":"Isparta"},
    {"code":"TR","name":"Burdur"},
    {"code":"TR","name":"Adana, Mersin"},
    {"code":"TR","name":"Adana"},
    {"code":"TR","name":"Mersin"},
    {"code":"TR","name":"Hatay, Kahramanmaraş, Osmaniye"},
    {"code":"TR","name":"Hatay"},
    {"code":"TR","name":"Kahramanmaraş"},
    {"code":"TR","name":"Osmaniye"},
    {"code":"TR","name":"Orta Anadolu"},
    {"code":"TR","name":"Kırıkkale, Aksaray, Niğde, Nevşehir, Kırşehir"},
    {"code":"TR","name":"Kırıkkale"},
    {"code":"TR","name":"Aksaray"},
    {"code":"TR","name":"Niğde"},
    {"code":"DE","name":"Dresden, Kreisfreie Stadt"},
    {"code":"DE","name":"Bautzen"},
    {"code":"DE","name":"Görlitz"},
    {"code":"DE","name":"Meißen"},
    {"code":"DE","name":"Sächsische Schweiz-Osterzgebirge"},
    {"code":"DE","name":"Chemnitz"},
    {"code":"DE","name":"Chemnitz, Kreisfreie Stadt"},
    {"code":"DE","name":"Erzgebirgskreis"},
    {"code":"DE","name":"Mittelsachsen"},
    {"code":"DE","name":"Vogtlandkreis"},
    {"code":"DE","name":"Zwickau"},
    {"code":"DE","name":"Leipzig"},
    {"code":"DE","name":"Leipzig, Kreisfreie Stadt"},
    {"code":"DE","name":"Leipzig"},
    {"code":"DE","name":"Nordsachsen"},
    {"code":"DE","name":"Sachsen-Anhalt"},
    {"code":"DE","name":"Sachsen-Anhalt"},
    {"code":"DE","name":"Dessau-Roßlau, Kreisfreie Stadt"},
    {"code":"DE","name":"Halle (Saale), Kreisfreie Stadt"},
    {"code":"DE","name":"Magdeburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Altmarkkreis Salzwedel"},
    {"code":"DE","name":"Anhalt-Bitterfeld"},
    {"code":"DE","name":"Jerichower Land"},
    {"code":"DE","name":"Börde"},
    {"code":"DE","name":"Burgenlandkreis"},
    {"code":"DE","name":"Harz"},
    {"code":"DE","name":"Mansfeld-Südharz"},
    {"code":"DE","name":"Saalekreis"},
    {"code":"DE","name":"Salzlandkreis"},
    {"code":"DE","name":"Stendal"},
    {"code":"DE","name":"Wittenberg"},
    {"code":"DE","name":"Schleswig-Holstein"},
    {"code":"DE","name":"Schleswig-Holstein"},
    {"code":"DE","name":"Flensburg, Kreisfreie Stadt"},
    {"code":"DE","name":"Kiel, Kreisfreie Stadt"},
    {"code":"DE","name":"Lübeck, Kreisfreie Stadt"},
    {"code":"DE","name":"Neumünster, Kreisfreie Stadt"},
    {"code":"DE","name":"Dithmarschen"},
    {"code":"DE","name":"Herzogtum Lauenburg"},
    {"code":"DE","name":"Nordfriesland"},
    {"code":"DE","name":"Ostholstein"},
    {"code":"DE","name":"Pinneberg"},
    {"code":"DE","name":"Plön"},
    {"code":"DE","name":"Rendsburg-Eckernförde"},
    {"code":"DE","name":"Schleswig-Flensburg"},
    {"code":"DE","name":"Segeberg"},
    {"code":"DE","name":"Steinburg"},
    {"code":"DE","name":"Stormarn"},
    {"code":"DE","name":"Thüringen"},
    {"code":"DE","name":"Thüringen"},
    {"code":"DE","name":"Erfurt, Kreisfreie Stadt"},
    {"code":"DE","name":"Gera, Kreisfreie Stadt"},
    {"code":"DE","name":"Jena, Kreisfreie Stadt"},
    {"code":"DE","name":"Suhl, Kreisfreie Stadt"},
    {"code":"DE","name":"Weimar, Kreisfreie Stadt"},
    {"code":"DE","name":"Eichsfeld"},
    {"code":"DE","name":"Nordhausen"},
    {"code":"DE","name":"Unstrut-Hainich-Kreis"},
    {"code":"DE","name":"Kyffhäuserkreis"},
    {"code":"DE","name":"Schmalkalden-Meiningen"},
    {"code":"DE","name":"Gotha"},
    {"code":"DE","name":"Sömmerda"},
    {"code":"DE","name":"Hildburghausen"},
    {"code":"DE","name":"Ilm-Kreis"},
    {"code":"DE","name":"Weimarer Land"},
    {"code":"DE","name":"Sonneberg"},
    {"code":"DE","name":"Saalfeld-Rudolstadt"},
    {"code":"DE","name":"Saale-Holzland-Kreis"},
    {"code":"DE","name":"Saale-Orla-Kreis"},
    {"code":"DE","name":"Greiz"},
    {"code":"DE","name":"Altenburger Land"},
    {"code":"DE","name":"Eisenach, Kreisfreie Stadt"},
    {"code":"DE","name":"Wartburgkreis"},
    {"code":"DK","name":"Danmark"},
    {"code":"DK","name":"Danmark"},
    {"code":"DK","name":"Hovedstaden"},
    {"code":"DK","name":"Byen København"},
    {"code":"DK","name":"Københavns omegn"},
    {"code":"DK","name":"Nordsjælland"},
    {"code":"DK","name":"Bornholm"},
    {"code":"DK","name":"Sjælland"},
    {"code":"DK","name":"Østsjælland"},
    {"code":"DK","name":"Vest- og Sydsjælland"},
    {"code":"DK","name":"Syddanmark"},
    {"code":"DK","name":"Fyn"},
    {"code":"DK","name":"Sydjylland"},
    {"code":"DK","name":"Midtjylland"},
    {"code":"DK","name":"Vestjylland"},
    {"code":"DK","name":"Østjylland"},
    {"code":"DK","name":"Nordjylland"},
    {"code":"DK","name":"Nordjylland"},
    {"code":"EE","name":"Eesti"},
    {"code":"EE","name":"Eesti"},
    {"code":"EE","name":"Eesti"},
    {"code":"EE","name":"Põhja-Eesti"},
    {"code":"EE","name":"Lääne-Eesti"},
    {"code":"EE","name":"Lõuna-Eesti"},
    {"code":"EE","name":"Kesk-Eesti"},
    {"code":"EE","name":"Kirde-Eesti"},
    {"code":"EL","name":"Elláda"},
    {"code":"EL","name":"Attiki"},
    {"code":"EL","name":"Attiki"},
    {"code":"EL","name":"Voreios Tomeas Athinon"},
    {"code":"EL","name":"Dytikos Tomeas Athinon"},
    {"code":"EL","name":"Kentrikos Tomeas Athinon"},
    {"code":"EL","name":"Notios Tomeas Athinon"},
    {"code":"EL","name":"Anatoliki Attiki"},
    {"code":"EL","name":"Dytiki Attiki"},
    {"code":"EL","name":"Peiraias, Nisoi"},
    {"code":"EL","name":"Nisia Aigaiou, Kriti"},
    {"code":"EL","name":"Voreio Aigaio"},
    {"code":"EL","name":"Lesvos, Limnos"},
    {"code":"EL","name":"Ikaria, Samos"},
    {"code":"EL","name":"Chios"},
    {"code":"EL","name":"Notio Aigaio"},
    {"code":"EL","name":"Kalymnos, Karpathos, Kasos, Kos, Rodos"},
    {"code":"EL","name":"Andros, Thira, Kea, Milos, Mykonos, Naxos, Paros,  Syros, Tinos"},
    {"code":"EL","name":"Kriti"},
    {"code":"EL","name":"Irakleio"},
    {"code":"EL","name":"Lasithi"},
    {"code":"EL","name":"Rethymni"},
    {"code":"EL","name":"Chania"},
    {"code":"EL","name":"Voreia Elláda"},
    {"code":"EL","name":"Anatoliki Makedonia, Thraki"},
    {"code":"EL","name":"Evros"},
    {"code":"EL","name":"Xanthi"},
    {"code":"EL","name":"Rodopi"},
    {"code":"EL","name":"Drama"},
    {"code":"EL","name":"Thasos, Kavala"},
    {"code":"EL","name":"Kentriki Makedonia"},
    {"code":"EL","name":"Imathia"},
    {"code":"EL","name":"Thessaloniki"},
    {"code":"EL","name":"Kilkis"},
    {"code":"EL","name":"Pella"},
    {"code":"EL","name":"Pieria"},
    {"code":"EL","name":"Serres"},
    {"code":"EL","name":"Chalkidiki"},
    {"code":"EL","name":"Dytiki Makedonia"},
    {"code":"EL","name":"Grevena, Kozani"},
    {"code":"EL","name":"Kastoria"},
    {"code":"EL","name":"Florina"},
    {"code":"EL","name":"Ipeiros"},
    {"code":"EL","name":"Arta, Preveza"},
    {"code":"EL","name":"Thesprotia"},
    {"code":"EL","name":"Ioannina"},
    {"code":"EL","name":"Kentriki Elláda"},
    {"code":"EL","name":"Thessalia"},
    {"code":"EL","name":"Karditsa, Trikala"},
    {"code":"EL","name":"Larisa"},
    {"code":"EL","name":"Magnisia, Sporades"},
    {"code":"EL","name":"Ionia Nisia"},
    {"code":"EL","name":"Zakynthos"},
    {"code":"EL","name":"Kerkyra"},
    {"code":"EL","name":"Ithaki, Kefallinia"},
    {"code":"EL","name":"Lefkada"},
    {"code":"EL","name":"Dytiki Elláda"},
    {"code":"EL","name":"Aitoloakarnania"},
    {"code":"EL","name":"Achaia"},
    {"code":"EL","name":"Ileia"},
    {"code":"EL","name":"Sterea Elláda"},
    {"code":"EL","name":"Voiotia"},
    {"code":"EL","name":"Evvoia"},
    {"code":"EL","name":"Evrytania"},
    {"code":"EL","name":"Fthiotida"},
    {"code":"EL","name":"Fokida"},
    {"code":"EL","name":"Peloponnisos"},
    {"code":"EL","name":"Argolida, Arkadia"},
    {"code":"EL","name":"Korinthia"},
    {"code":"EL","name":"Lakonia, Messinia"},
    {"code":"ES","name":"España"},
    {"code":"ES","name":"Noroeste"},
    {"code":"ES","name":"Galicia"},
    {"code":"ES","name":"A Coruña"},
    {"code":"ES","name":"Lugo"},
    {"code":"ES","name":"Ourense"},
    {"code":"ES","name":"Pontevedra"},
    {"code":"ES","name":"Principado de Asturias"},
    {"code":"ES","name":"Asturias"},
    {"code":"ES","name":"Cantabria"},
    {"code":"ES","name":"Cantabria"},
    {"code":"ES","name":"Noreste"},
    {"code":"ES","name":"País Vasco"},
    {"code":"ES","name":"Araba/Álava"},
    {"code":"ES","name":"Gipuzkoa"},
    {"code":"ES","name":"Bizkaia"},
    {"code":"ES","name":"Comunidad Foral de Navarra"},
    {"code":"ES","name":"Navarra"},
    {"code":"ES","name":"La Rioja"},
    {"code":"ES","name":"La Rioja"},
    {"code":"ES","name":"Aragón"},
    {"code":"ES","name":"Huesca"},
    {"code":"ES","name":"Teruel"},
    {"code":"ES","name":"Zaragoza"},
    {"code":"ES","name":"Comunidad de Madrid"},
    {"code":"ES","name":"Comunidad de Madrid"},
    {"code":"ES","name":"Madrid"},
    {"code":"ES","name":"Centro (ES)"},
    {"code":"ES","name":"Castilla y León"},
    {"code":"ES","name":"Ávila"},
    {"code":"ES","name":"Burgos"},
    {"code":"ES","name":"León"},
    {"code":"ES","name":"Palencia"},
    {"code":"ES","name":"Salamanca"},
    {"code":"ES","name":"Segovia"},
    {"code":"ES","name":"Soria"},
    {"code":"ES","name":"Valladolid"},
    {"code":"ES","name":"Zamora"},
    {"code":"ES","name":"Castilla-La Mancha"},
    {"code":"ES","name":"Albacete"},
    {"code":"ES","name":"Ciudad Real"},
    {"code":"ES","name":"Cuenca"},
    {"code":"ES","name":"Guadalajara"},
    {"code":"ES","name":"Toledo"},
    {"code":"ES","name":"Extremadura"},
    {"code":"ES","name":"Badajoz"},
    {"code":"ES","name":"Cáceres"},
    {"code":"ES","name":"Este"},
    {"code":"ES","name":"Cataluña"},
    {"code":"ES","name":"Barcelona"},
    {"code":"ES","name":"Girona"},
    {"code":"ES","name":"Lleida"},
    {"code":"ES","name":"Tarragona"},
    {"code":"ES","name":"Comunitat Valenciana"},
    {"code":"ES","name":"Alicante/Alacant"},
    {"code":"ES","name":"Castellón/Castelló"},
    {"code":"ES","name":"Valencia/València"},
    {"code":"ES","name":"Illes Balears"},
    {"code":"ES","name":"Eivissa y Formentera"},
    {"code":"ES","name":"Mallorca"},
    {"code":"ES","name":"Menorca"},
    {"code":"ES","name":"Sur"},
    {"code":"ES","name":"Andalucía"},
    {"code":"ES","name":"Almería"},
    {"code":"ES","name":"Cádiz"},
    {"code":"ES","name":"Córdoba"},
    {"code":"ES","name":"Granada"},
    {"code":"ES","name":"Huelva"},
    {"code":"ES","name":"Jaén"},
    {"code":"ES","name":"Málaga"},
    {"code":"ES","name":"Sevilla"},
    {"code":"ES","name":"Región de Murcia"},
    {"code":"ES","name":"Murcia"},
    {"code":"ES","name":"Ciudad de Ceuta"},
    {"code":"ES","name":"Ceuta"},
    {"code":"ES","name":"Ciudad de Melilla"},
    {"code":"ES","name":"Melilla"},
    {"code":"ES","name":"Canarias"},
    {"code":"ES","name":"Canarias"},
    {"code":"ES","name":"El Hierro"},
    {"code":"ES","name":"Fuerteventura"},
    {"code":"ES","name":"Gran Canaria"},
    {"code":"ES","name":"La Gomera"},
    {"code":"ES","name":"La Palma"},
    {"code":"ES","name":"Lanzarote"},
    {"code":"ES","name":"Tenerife"},
    {"code":"FI","name":"Suomi/Finland"},
    {"code":"FI","name":"Manner-Suomi"},
    {"code":"FI","name":"Länsi-Suomi"},
    {"code":"FI","name":"Keski-Suomi"},
    {"code":"FI","name":"Etelä-Pohjanmaa"},
    {"code":"FI","name":"Pohjanmaa"},
    {"code":"FI","name":"Satakunta"},
    {"code":"FI","name":"Pirkanmaa"},
    {"code":"FI","name":"Helsinki-Uusimaa"},
    {"code":"FI","name":"Helsinki-Uusimaa"},
    {"code":"FI","name":"Etelä-Suomi"},
    {"code":"FI","name":"Varsinais-Suomi"},
    {"code":"FI","name":"Kanta-Häme"},
    {"code":"FI","name":"Päijät-Häme"},
    {"code":"FI","name":"Kymenlaakso"},
    {"code":"FI","name":"Etelä-Karjala"},
    {"code":"FI","name":"Pohjois- ja Itä-Suomi"},
    {"code":"FI","name":"Etelä-Savo"},
    {"code":"FI","name":"Pohjois-Savo"},
    {"code":"FI","name":"Pohjois-Karjala"},
    {"code":"FI","name":"Keski-Pohjanmaa"},
    {"code":"FI","name":"Lappi"},
    {"code":"FI","name":"Kainuu"},
    {"code":"FI","name":"Pohjois-Pohjanmaa"},
    {"code":"FI","name":"Åland"},
    {"code":"FI","name":"Åland"},
    {"code":"FI","name":"Åland"},
    {"code":"FR","name":"France"},
    {"code":"FR","name":"Ile-de-France"},
    {"code":"FR","name":"Ile-de-France"},
    {"code":"FR","name":"Paris"},
    {"code":"FR","name":"Seine-et-Marne"},
    {"code":"FR","name":"Yvelines"},
    {"code":"FR","name":"Essonne"},
    {"code":"FR","name":"Hauts-de-Seine"},
    {"code":"FR","name":"Seine-Saint-Denis"},
    {"code":"FR","name":"Val-de-Marne"},
    {"code":"FR","name":"Val-d’Oise"},
    {"code":"FR","name":"Centre — Val de Loire"},
    {"code":"FR","name":"Centre — Val de Loire"},
    {"code":"FR","name":"Cher"},
    {"code":"FR","name":"Eure-et-Loir"},
    {"code":"FR","name":"Indre"},
    {"code":"FR","name":"Indre-et-Loire"},
    {"code":"FR","name":"Loir-et-Cher"},
    {"code":"FR","name":"Loiret"},
    {"code":"FR","name":"Bourgogne-Franche-Comté"},
    {"code":"FR","name":"Bourgogne"},
    {"code":"FR","name":"Côte-d’Or"},
    {"code":"FR","name":"Nièvre"},
    {"code":"FR","name":"Saône-et-Loire"},
    {"code":"FR","name":"Yonne"},
    {"code":"FR","name":"Franche-Comté"},
    {"code":"FR","name":"Doubs"},
    {"code":"FR","name":"Jura"},
    {"code":"FR","name":"Haute-Saône"},
    {"code":"FR","name":"Territoire de Belfort"},
    {"code":"FR","name":"Normandie"},
    {"code":"FR","name":"Basse-Normandie"},
    {"code":"FR","name":"Calvados"},
    {"code":"FR","name":"Manche"},
    {"code":"FR","name":"Orne"},
    {"code":"FR","name":"Haute-Normandie"},
    {"code":"FR","name":"Eure"},
    {"code":"FR","name":"Seine-Maritime"},
    {"code":"FR","name":"Hauts-de-France"},
    {"code":"FR","name":"Nord-Pas de Calais"},
    {"code":"FR","name":"Nord"},
    {"code":"FR","name":"Pas-de-Calais"},
    {"code":"FR","name":"Picardie"},
    {"code":"FR","name":"Aisne"},
    {"code":"FR","name":"Oise"},
    {"code":"FR","name":"Somme"},
    {"code":"FR","name":"Grand Est"},
    {"code":"FR","name":"Alsace"},
    {"code":"FR","name":"Bas-Rhin"},
    {"code":"FR","name":"Haut-Rhin"},
    {"code":"FR","name":"Champagne-Ardenne"},
    {"code":"FR","name":"Ardennes"},
    {"code":"FR","name":"Aube"},
    {"code":"FR","name":"Marne"},
    {"code":"FR","name":"Haute-Marne"},
    {"code":"FR","name":"Lorraine"},
    {"code":"FR","name":"Meurthe-et-Moselle"},
    {"code":"FR","name":"Meuse"},
    {"code":"FR","name":"Moselle"},
    {"code":"FR","name":"Vosges"},
    {"code":"FR","name":"Pays de la Loire"},
    {"code":"FR","name":"Pays de la Loire"},
    {"code":"FR","name":"Loire-Atlantique"},
    {"code":"FR","name":"Maine-et-Loire"},
    {"code":"FR","name":"Mayenne"},
    {"code":"FR","name":"Sarthe"},
    {"code":"FR","name":"Vendée"},
    {"code":"FR","name":"Bretagne"},
    {"code":"FR","name":"Bretagne"},
    {"code":"FR","name":"Côtes-d’Armor"},
    {"code":"FR","name":"Finistère"},
    {"code":"FR","name":"Ille-et-Vilaine"},
    {"code":"FR","name":"Morbihan"},
    {"code":"FR","name":"Nouvelle-Aquitaine"},
    {"code":"FR","name":"Aquitaine"},
    {"code":"FR","name":"Dordogne"},
    {"code":"FR","name":"Gironde"},
    {"code":"FR","name":"Landes"},
    {"code":"FR","name":"Lot-et-Garonne"},
    {"code":"FR","name":"Pyrénées-Atlantiques"},
    {"code":"FR","name":"Limousin"},
    {"code":"FR","name":"Corrèze"},
    {"code":"FR","name":"Creuse"},
    {"code":"FR","name":"Haute-Vienne"},
    {"code":"FR","name":"Poitou-Charentes"},
    {"code":"FR","name":"Charente"},
    {"code":"FR","name":"Charente-Maritime"},
    {"code":"FR","name":"Deux-Sèvres"},
    {"code":"FR","name":"Vienne"},
    {"code":"FR","name":"Occitanie"},
    {"code":"FR","name":"Languedoc-Roussillon"},
    {"code":"FR","name":"Aude"},
    {"code":"FR","name":"Gard"},
    {"code":"FR","name":"Hérault"},
    {"code":"FR","name":"Lozère"},
    {"code":"FR","name":"Pyrénées-Orientales"},
    {"code":"FR","name":"Midi-Pyrénées"},
    {"code":"FR","name":"Ariège"},
    {"code":"FR","name":"Aveyron"},
    {"code":"FR","name":"Haute-Garonne"},
    {"code":"FR","name":"Gers"},
    {"code":"FR","name":"Lot"},
    {"code":"FR","name":"Hautes-Pyrénées"},
    {"code":"FR","name":"Tarn"},
    {"code":"FR","name":"Tarn-et-Garonne"},
    {"code":"FR","name":"Auvergne-Rhône-Alpes"},
    {"code":"FR","name":"Auvergne"},
    {"code":"FR","name":"Allier"},
    {"code":"FR","name":"Cantal"},
    {"code":"FR","name":"Haute-Loire"},
    {"code":"FR","name":"Puy-de-Dôme"},
    {"code":"FR","name":"Rhône-Alpes"},
    {"code":"FR","name":"Ain"},
    {"code":"FR","name":"Ardèche"},
    {"code":"FR","name":"Drôme"},
    {"code":"FR","name":"Isère"},
    {"code":"FR","name":"Loire"},
    {"code":"FR","name":"Rhône"},
    {"code":"FR","name":"Savoie"},
    {"code":"FR","name":"Haute-Savoie"},
    {"code":"FR","name":"Provence-Alpes-Côte d’Azur"},
    {"code":"FR","name":"Provence-Alpes-Côte d’Azur"},
    {"code":"FR","name":"Alpes-de-Haute-Provence"},
    {"code":"FR","name":"Hautes-Alpes"},
    {"code":"FR","name":"Alpes-Maritimes"},
    {"code":"FR","name":"Bouches-du-Rhône"},
    {"code":"FR","name":"Var"},
    {"code":"FR","name":"Vaucluse"},
    {"code":"FR","name":"Corse"},
    {"code":"FR","name":"Corse"},
    {"code":"FR","name":"Corse-du-Sud"},
    {"code":"FR","name":"Haute-Corse"},
    {"code":"FR","name":"RUP FR — Régions Ultrapériphériques Françaises"},
    {"code":"FR","name":"Guadeloupe"},
    {"code":"FR","name":"Guadeloupe"},
    {"code":"FR","name":"Martinique"},
    {"code":"FR","name":"Martinique"},
    {"code":"FR","name":"Guyane"},
    {"code":"FR","name":"Guyane"},
    {"code":"FR","name":"La Réunion"},
    {"code":"FR","name":"La Réunion"},
    {"code":"FR","name":"Mayotte"},
    {"code":"FR","name":"Mayotte"},
    {"code":"HR","name":"Hrvatska"},
    {"code":"HR","name":"Hrvatska"},
    {"code":"HR","name":"Panonska Hrvatska"},
    {"code":"HR","name":"Bjelovarsko-bilogorska županija"},
    {"code":"HR","name":"Virovitičko-podravska županija"},
    {"code":"HR","name":"Požeško-slavonska županija"},
    {"code":"HR","name":"Brodsko-posavska županija"},
    {"code":"HR","name":"Osječko-baranjska županija"},
    {"code":"HR","name":"Vukovarsko-srijemska županija"},
    {"code":"HR","name":"Karlovačka županija"},
    {"code":"HR","name":"Sisačko-moslavačka županija"},
    {"code":"HR","name":"Jadranska Hrvatska"},
    {"code":"HR","name":"Primorsko-goranska županija"},
    {"code":"HR","name":"Ličko-senjska županija"},
    {"code":"HR","name":"Zadarska županija"},
    {"code":"HR","name":"Šibensko-kninska županija"},
    {"code":"HR","name":"Splitsko-dalmatinska županija"},
    {"code":"HR","name":"Istarska županija"},
    {"code":"HR","name":"Dubrovačko-neretvanska županija"},
    {"code":"HR","name":"Grad Zagreb"},
    {"code":"HR","name":"Grad Zagreb"},
    {"code":"HR","name":"Sjeverna Hrvatska"},
    {"code":"HR","name":"Međimurska županija"},
    {"code":"HR","name":"Varaždinska županija"},
    {"code":"HR","name":"Koprivničko-križevačka županija"},
    {"code":"HR","name":"Krapinsko-zagorska županija"},
    {"code":"HR","name":"Zagrebačka županija"},
    {"code":"HU","name":"Magyarország"},
    {"code":"HU","name":"Közép-Magyarország"},
    {"code":"HU","name":"Budapest"},
    {"code":"HU","name":"Budapest"},
    {"code":"HU","name":"Pest"},
    {"code":"HU","name":"Pest"},
    {"code":"HU","name":"Dunántúl"},
    {"code":"HU","name":"Közép-Dunántúl"},
    {"code":"HU","name":"Fejér"},
    {"code":"HU","name":"Komárom-Esztergom"},
    {"code":"HU","name":"Veszprém"},
    {"code":"HU","name":"Nyugat-Dunántúl"},
    {"code":"HU","name":"Győr-Moson-Sopron"},
    {"code":"HU","name":"Vas"},
    {"code":"HU","name":"Zala"},
    {"code":"HU","name":"Dél-Dunántúl"},
    {"code":"HU","name":"Baranya"},
    {"code":"HU","name":"Somogy"},
    {"code":"HU","name":"Tolna"},
    {"code":"HU","name":"Alföld és Észak"},
    {"code":"HU","name":"Észak-Magyarország"},
    {"code":"HU","name":"Borsod-Abaúj-Zemplén"},
    {"code":"HU","name":"Heves"},
    {"code":"HU","name":"Nógrád"},
    {"code":"HU","name":"Észak-Alföld"},
    {"code":"HU","name":"Hajdú-Bihar"},
    {"code":"HU","name":"Jász-Nagykun-Szolnok"},
    {"code":"HU","name":"Szabolcs-Szatmár-Bereg"},
    {"code":"HU","name":"Dél-Alföld"},
    {"code":"HU","name":"Bács-Kiskun"},
    {"code":"HU","name":"Békés"},
    {"code":"HU","name":"Csongrád"},
    {"code":"IE","name":"Éire/Ireland"},
    {"code":"IE","name":"Ireland"},
    {"code":"IE","name":"Northern and Western"},
    {"code":"IE","name":"Border"},
    {"code":"IE","name":"West"},
    {"code":"IE","name":"Southern"},
    {"code":"IE","name":"Mid-West"},
    {"code":"IE","name":"South-East"},
    {"code":"IE","name":"South-West"},
    {"code":"IE","name":"Eastern and Midland"},
    {"code":"IE","name":"Dublin"},
    {"code":"IE","name":"Mid-East"},
    {"code":"IE","name":"Midland"},
    {"code":"IS","name":"Ísland"},
    {"code":"IS","name":"Ísland"},
    {"code":"IS","name":"Ísland"},
    {"code":"IS","name":"Höfuðborgarsvæði"},
    {"code":"IS","name":"Landsbyggð"},
    {"code":"IT","name":"Italia"},
    {"code":"IT","name":"Nord-Ovest"},
    {"code":"IT","name":"Piemonte"},
    {"code":"IT","name":"Torino"},
    {"code":"IT","name":"Vercelli"},
    {"code":"IT","name":"Biella"},
    {"code":"IT","name":"Verbano-Cusio-Ossola"},
    {"code":"IT","name":"Novara"},
    {"code":"IT","name":"Cuneo"},
    {"code":"IT","name":"Asti"},
    {"code":"IT","name":"Alessandria"},
    {"code":"IT","name":"Valle d’Aosta/Vallée d’Aoste"},
    {"code":"IT","name":"Valle d’Aosta/Vallée d’Aoste"},
    {"code":"IT","name":"Liguria"},
    {"code":"IT","name":"Imperia"},
    {"code":"IT","name":"Savona"},
    {"code":"IT","name":"Genova"},
    {"code":"IT","name":"La Spezia"},
    {"code":"IT","name":"Lombardia"},
    {"code":"IT","name":"Varese"},
    {"code":"IT","name":"Como"},
    {"code":"IT","name":"Lecco"},
    {"code":"IT","name":"Sondrio"},
    {"code":"IT","name":"Bergamo"},
    {"code":"IT","name":"Brescia"},
    {"code":"IT","name":"Pavia"},
    {"code":"IT","name":"Lodi"},
    {"code":"IT","name":"Cremona"},
    {"code":"IT","name":"Mantova"},
    {"code":"IT","name":"Milano"},
    {"code":"IT","name":"Monza e della Brianza"},
    {"code":"IT","name":"Sud"},
    {"code":"IT","name":"Abruzzo"},
    {"code":"IT","name":"L’Aquila"},
    {"code":"IT","name":"Teramo"},
    {"code":"IT","name":"Pescara"},
    {"code":"IT","name":"Chieti"},
    {"code":"IT","name":"Molise"},
    {"code":"IT","name":"Isernia"},
    {"code":"IT","name":"Campobasso"},
    {"code":"IT","name":"Campania"},
    {"code":"IT","name":"Caserta"},
    {"code":"IT","name":"Benevento"},
    {"code":"IT","name":"Napoli"},
    {"code":"IT","name":"Avellino"},
    {"code":"IT","name":"Salerno"},
    {"code":"IT","name":"Puglia"},
    {"code":"IT","name":"Taranto"},
    {"code":"IT","name":"Brindisi"},
    {"code":"IT","name":"Lecce"},
    {"code":"IT","name":"Foggia"},
    {"code":"IT","name":"Bari"},
    {"code":"IT","name":"Barletta-Andria-Trani"},
    {"code":"IT","name":"Basilicata"},
    {"code":"IT","name":"Potenza"},
    {"code":"IT","name":"Matera"},
    {"code":"IT","name":"Calabria"},
    {"code":"IT","name":"Cosenza"},
    {"code":"IT","name":"Crotone"},
    {"code":"IT","name":"Catanzaro"},
    {"code":"IT","name":"Vibo Valentia"},
    {"code":"IT","name":"Reggio di Calabria"},
    {"code":"IT","name":"Isole"},
    {"code":"IT","name":"Sicilia"},
    {"code":"IT","name":"Trapani"},
    {"code":"IT","name":"Palermo"},
    {"code":"IT","name":"Messina"},
    {"code":"IT","name":"Agrigento"},
    {"code":"IT","name":"Caltanissetta"},
    {"code":"IT","name":"Enna"},
    {"code":"IT","name":"Catania"},
    {"code":"IT","name":"Ragusa"},
    {"code":"IT","name":"Siracusa"},
    {"code":"IT","name":"Sardegna"},
    {"code":"IT","name":"Sassari"},
    {"code":"IT","name":"Nuoro"},
    {"code":"IT","name":"Cagliari"},
    {"code":"IT","name":"Oristano"},
    {"code":"IT","name":"Sud Sardegna"},
    {"code":"IT","name":"Nord-Est"},
    {"code":"IT","name":"Provincia Autonoma di Bolzano/Bozen"},
    {"code":"IT","name":"Bolzano-Bozen"},
    {"code":"IT","name":"Provincia Autonoma di Trento"},
    {"code":"IT","name":"Trento"},
    {"code":"IT","name":"Veneto"},
    {"code":"IT","name":"Verona"},
    {"code":"IT","name":"Vicenza"},
    {"code":"IT","name":"Belluno"},
    {"code":"IT","name":"Treviso"},
    {"code":"IT","name":"Venezia"},
    {"code":"IT","name":"Padova"},
    {"code":"IT","name":"Rovigo"},
    {"code":"IT","name":"Friuli-Venezia Giulia"},
    {"code":"IT","name":"Pordenone"},
    {"code":"IT","name":"Udine"},
    {"code":"IT","name":"Gorizia"},
    {"code":"IT","name":"Trieste"},
    {"code":"IT","name":"Emilia-Romagna"},
    {"code":"IT","name":"Piacenza"},
    {"code":"IT","name":"Parma"},
    {"code":"IT","name":"Reggio nell’Emilia"},
    {"code":"IT","name":"Modena"},
    {"code":"IT","name":"Bologna"},
    {"code":"IT","name":"Ferrara"},
    {"code":"IT","name":"Ravenna"},
    {"code":"IT","name":"Forlì-Cesena"},
    {"code":"IT","name":"Rimini"},
    {"code":"IT","name":"Centro (IT)"},
    {"code":"IT","name":"Toscana"},
    {"code":"IT","name":"Massa-Carrara"},
    {"code":"IT","name":"Lucca"},
    {"code":"IT","name":"Pistoia"},
    {"code":"IT","name":"Firenze"},
    {"code":"IT","name":"Prato"},
    {"code":"IT","name":"Livorno"},
    {"code":"IT","name":"Pisa"},
    {"code":"IT","name":"Arezzo"},
    {"code":"IT","name":"Siena"},
    {"code":"IT","name":"Grosseto"},
    {"code":"IT","name":"Umbria"},
    {"code":"IT","name":"Perugia"},
    {"code":"IT","name":"Terni"},
    {"code":"IT","name":"Marche"},
    {"code":"IT","name":"Pesaro e Urbino"},
    {"code":"IT","name":"Ancona"},
    {"code":"IT","name":"Macerata"},
    {"code":"IT","name":"Ascoli Piceno"},
    {"code":"IT","name":"Fermo"},
    {"code":"IT","name":"Lazio"},
    {"code":"IT","name":"Viterbo"},
    {"code":"IT","name":"Rieti"},
    {"code":"IT","name":"Roma"},
    {"code":"IT","name":"Latina"},
    {"code":"IT","name":"Frosinone"},
    {"code":"LI","name":"Liechtenstein"},
    {"code":"LI","name":"Liechtenstein"},
    {"code":"LI","name":"Liechtenstein"},
    {"code":"LI","name":"Liechtenstein"},
    {"code":"LT","name":"Lietuva"},
    {"code":"LT","name":"Lietuva"},
    {"code":"LT","name":"Sostinės regionas"},
    {"code":"LT","name":"Vilniaus apskritis"},
    {"code":"LT","name":"Vidurio ir vakarų Lietuvos regionas"},
    {"code":"LT","name":"Alytaus apskritis"},
    {"code":"LT","name":"Kauno apskritis"},
    {"code":"LT","name":"Klaipėdos apskritis"},
    {"code":"LT","name":"Marijampolės apskritis"},
    {"code":"LT","name":"Panevėžio apskritis"},
    {"code":"LT","name":"Šiaulių apskritis"},
    {"code":"LT","name":"Tauragės apskritis"},
    {"code":"LT","name":"Telšių apskritis"},
    {"code":"LT","name":"Utenos apskritis"},
    {"code":"LU","name":"Luxembourg"},
    {"code":"LU","name":"Luxembourg"},
    {"code":"LU","name":"Luxembourg"},
    {"code":"LU","name":"Luxembourg"},
    {"code":"LV","name":"Latvija"},
    {"code":"LV","name":"Latvija"},
    {"code":"LV","name":"Latvija"},
    {"code":"LV","name":"Kurzeme"},
    {"code":"LV","name":"Latgale"},
    {"code":"LV","name":"Rīga"},
    {"code":"LV","name":"Pierīga"},
    {"code":"LV","name":"Vidzeme"},
    {"code":"LV","name":"Zemgale"},
    {"code":"ME","name":"Crna Gora"},
    {"code":"ME","name":"Crna Gora"},
    {"code":"ME","name":"Crna Gora"},
    {"code":"ME","name":"Crna Gora"},
    {"code":"MK","name":"Severna Makedonija"},
    {"code":"MK","name":"Severna Makedonija"},
    {"code":"MK","name":"Severna Makedonija"},
    {"code":"MK","name":"Vardarski"},
    {"code":"MK","name":"Istočen"},
    {"code":"MK","name":"Jugozapaden"},
    {"code":"MK","name":"Jugoistočen"},
    {"code":"MK","name":"Pelagoniski"},
    {"code":"MK","name":"Pološki"},
    {"code":"MK","name":"Severoistočen"},
    {"code":"MK","name":"Skopski"},
    {"code":"MT","name":"Malta"},
    {"code":"MT","name":"Malta"},
    {"code":"MT","name":"Malta"},
    {"code":"MT","name":"Malta"},
    {"code":"MT","name":"Gozo and Comino/Għawdex u Kemmuna"},
    {"code":"NL","name":"Nederland"},
    {"code":"NL","name":"Noord-Nederland"},
    {"code":"NL","name":"Groningen"},
    {"code":"NL","name":"Oost-Groningen"},
    {"code":"NL","name":"Delfzijl en omgeving"},
    {"code":"NL","name":"Overig Groningen"},
    {"code":"NL","name":"Friesland (NL)"},
    {"code":"NL","name":"Noord-Friesland"},
    {"code":"NL","name":"Zuidwest-Friesland"},
    {"code":"NL","name":"Zuidoost-Friesland"},
    {"code":"NL","name":"Drenthe"},
    {"code":"NL","name":"Noord-Drenthe"},
    {"code":"NL","name":"Zuidoost-Drenthe"},
    {"code":"NL","name":"Zuidwest-Drenthe"},
    {"code":"NL","name":"Oost-Nederland"},
    {"code":"NL","name":"Overijssel"},
    {"code":"NL","name":"Noord-Overijssel"},
    {"code":"NL","name":"Zuidwest-Overijssel"},
    {"code":"NL","name":"Twente"},
    {"code":"NL","name":"Gelderland"},
    {"code":"NL","name":"Veluwe"},
    {"code":"NL","name":"Zuidwest-Gelderland"},
    {"code":"NL","name":"Achterhoek"},
    {"code":"NL","name":"Arnhem/Nijmegen"},
    {"code":"NL","name":"Flevoland"},
    {"code":"NL","name":"Flevoland"},
    {"code":"NL","name":"West-Nederland"},
    {"code":"NL","name":"Utrecht"},
    {"code":"NL","name":"Utrecht"},
    {"code":"NL","name":"Noord-Holland"},
    {"code":"NL","name":"Kop van Noord-Holland"},
    {"code":"NL","name":"IJmond"},
    {"code":"NL","name":"Agglomeratie Haarlem"},
    {"code":"NL","name":"Zaanstreek"},
    {"code":"NL","name":"Het Gooi en Vechtstreek"},
    {"code":"NL","name":"Alkmaar en omgeving"},
    {"code":"NL","name":"Groot-Amsterdam"},
    {"code":"NL","name":"Zuid-Holland"},
    {"code":"NL","name":"Agglomeratie ’s-Gravenhage"},
    {"code":"NL","name":"Delft en Westland"},
    {"code":"NL","name":"Agglomeratie Leiden en Bollenstreek"},
    {"code":"NL","name":"Zuidoost-Zuid-Holland"},
    {"code":"NL","name":"Oost-Zuid-Holland"},
    {"code":"NL","name":"Groot-Rijnmond"},
    {"code":"NL","name":"Zeeland"},
    {"code":"NL","name":"Zeeuwsch-Vlaanderen"},
    {"code":"NL","name":"Overig Zeeland"},
    {"code":"NL","name":"Zuid-Nederland"},
    {"code":"NL","name":"Noord-Brabant"},
    {"code":"NL","name":"West-Noord-Brabant"},
    {"code":"NL","name":"Midden-Noord-Brabant"},
    {"code":"NL","name":"Noordoost-Noord-Brabant"},
    {"code":"NL","name":"Zuidoost-Noord-Brabant"},
    {"code":"NL","name":"Limburg (NL)"},
    {"code":"NL","name":"Noord-Limburg"},
    {"code":"NL","name":"Midden-Limburg"},
    {"code":"NL","name":"Zuid-Limburg"},
    {"code":"NO","name":"Norge"},
    {"code":"NO","name":"Norge"},
    {"code":"NO","name":"Innlandet"},
    {"code":"NO","name":"Innlandet"},
    {"code":"NO","name":"Trøndelag"},
    {"code":"NO","name":"Trøndelag"},
    {"code":"NO","name":"Nord-Norge"},
    {"code":"NO","name":"Nordland"},
    {"code":"NO","name":"Troms og Finnmark"},
    {"code":"NO","name":"Oslo og Viken"},
    {"code":"NO","name":"Oslo"},
    {"code":"NO","name":"Viken"},
    {"code":"NO","name":"Agder og Sør-Østlandet"},
    {"code":"NO","name":"Vestfold og Telemark"},
    {"code":"NO","name":"Agder"},
    {"code":"NO","name":"Vestlandet"},
    {"code":"NO","name":"Rogaland"},
    {"code":"NO","name":"Vestland"},
    {"code":"NO","name":"Møre og Romsdal"},
    {"code":"PL","name":"Polska"},
    {"code":"PL","name":"Makroregion południowy"},
    {"code":"PL","name":"Małopolskie"},
    {"code":"PL","name":"Miasto Kraków"},
    {"code":"PL","name":"Krakowski"},
    {"code":"PL","name":"Tarnowski"},
    {"code":"PL","name":"Nowosądecki"},
    {"code":"PL","name":"Nowotarski"},
    {"code":"PL","name":"Oświęcimski"},
    {"code":"PL","name":"Śląskie"},
    {"code":"PL","name":"Częstochowski"},
    {"code":"PL","name":"Bielski"},
    {"code":"PL","name":"Rybnicki"},
    {"code":"PL","name":"Bytomski"},
    {"code":"PL","name":"Gliwicki"},
    {"code":"PL","name":"Katowicki"},
    {"code":"PL","name":"Sosnowiecki"},
    {"code":"PL","name":"Tyski"},
    {"code":"PL","name":"Makroregion północno-zachodni"},
    {"code":"PL","name":"Wielkopolskie"},
    {"code":"PL","name":"Pilski"},
    {"code":"PL","name":"Koniński"},
    {"code":"PL","name":"Miasto Poznań"},
    {"code":"PL","name":"Kaliski"},
    {"code":"PL","name":"Leszczyński"},
    {"code":"PL","name":"Poznański"},
    {"code":"PL","name":"Zachodniopomorskie"},
    {"code":"PL","name":"Miasto Szczecin"},
    {"code":"PL","name":"Koszaliński"},
    {"code":"PL","name":"Szczecinecko-pyrzycki"},
    {"code":"PL","name":"Szczeciński"},
    {"code":"PL","name":"Lubuskie"},
    {"code":"PL","name":"Gorzowski"},
    {"code":"PL","name":"Zielonogórski"},
    {"code":"PL","name":"Makroregion południowo-zachodni"},
    {"code":"PL","name":"Dolnośląskie"},
    {"code":"PL","name":"Miasto Wrocław"},
    {"code":"PL","name":"Jeleniogórski"},
    {"code":"PL","name":"Legnicko-głogowski"},
    {"code":"PL","name":"Wałbrzyski"},
    {"code":"PL","name":"Wrocławski"},
    {"code":"PL","name":"Opolskie"},
    {"code":"PL","name":"Nyski"},
    {"code":"PL","name":"Opolski"},
    {"code":"PL","name":"Makroregion północny"},
    {"code":"PL","name":"Kujawsko-pomorskie"},
    {"code":"PL","name":"Bydgosko-toruński"},
    {"code":"PL","name":"Grudziądzki"},
    {"code":"PL","name":"Inowrocławski"},
    {"code":"PL","name":"Świecki"},
    {"code":"PL","name":"Włocławski"},
    {"code":"PL","name":"Warmińsko-mazurskie"},
    {"code":"PL","name":"Elbląski"},
    {"code":"PL","name":"Olsztyński"},
    {"code":"PL","name":"Ełcki"},
    {"code":"PL","name":"Pomorskie"},
    {"code":"PL","name":"Trójmiejski"},
    {"code":"PL","name":"Gdański"},
    {"code":"PL","name":"Słupski"},
    {"code":"PL","name":"Chojnicki"},
    {"code":"PL","name":"Starogardzki"},
    {"code":"PL","name":"Makroregion centralny"},
    {"code":"PL","name":"Łódzkie"},
    {"code":"PL","name":"Miasto Łódź"},
    {"code":"PL","name":"Łódzki"},
    {"code":"PL","name":"Piotrkowski"},
    {"code":"PL","name":"Sieradzki"},
    {"code":"PL","name":"Skierniewicki"},
    {"code":"PL","name":"Świętokrzyskie"},
    {"code":"PL","name":"Kielecki"},
    {"code":"PL","name":"Sandomiersko-jędrzejowski"},
    {"code":"PL","name":"Makroregion wschodni"},
    {"code":"PL","name":"Lubelskie"},
    {"code":"PL","name":"Bialski"},
    {"code":"PL","name":"Chełmsko-zamojski"},
    {"code":"PL","name":"Lubelski"},
    {"code":"PL","name":"Puławski"},
    {"code":"PL","name":"Podkarpackie"},
    {"code":"PL","name":"Krośnieński"},
    {"code":"PL","name":"Przemyski"},
    {"code":"PL","name":"Rzeszowski"},
    {"code":"PL","name":"Tarnobrzeski"},
    {"code":"PL","name":"Podlaskie"},
    {"code":"PL","name":"Białostocki"},
    {"code":"PL","name":"Łomżyński"},
    {"code":"PL","name":"Suwalski"},
    {"code":"PL","name":"Makroregion województwo mazowieckie"},
    {"code":"PL","name":"Warszawski stołeczny"},
    {"code":"PL","name":"Miasto Warszawa"},
    {"code":"PL","name":"Warszawski wschodni"},
    {"code":"PL","name":"Warszawski zachodni"},
    {"code":"PL","name":"Mazowiecki regionalny"},
    {"code":"PL","name":"Radomski"},
    {"code":"PL","name":"Ciechanowski"},
    {"code":"PL","name":"Płocki"},
    {"code":"PL","name":"Ostrołęcki"},
    {"code":"PL","name":"Siedlecki"},
    {"code":"PL","name":"Żyrardowski"},
    {"code":"PT","name":"Portugal"},
    {"code":"PT","name":"Continente"},
    {"code":"PT","name":"Norte"},
    {"code":"PT","name":"Alto Minho"},
    {"code":"PT","name":"Cávado"},
    {"code":"PT","name":"Ave"},
    {"code":"PT","name":"Área Metropolitana do Porto"},
    {"code":"PT","name":"Alto Tâmega"},
    {"code":"PT","name":"Tâmega e Sousa"},
    {"code":"PT","name":"Douro"},
    {"code":"PT","name":"Terras de Trás-os-Montes"},
    {"code":"PT","name":"Algarve"},
    {"code":"PT","name":"Algarve"},
    {"code":"PT","name":"Centro (PT)"},
    {"code":"PT","name":"Oeste"},
    {"code":"PT","name":"Região de Aveiro"},
    {"code":"PT","name":"Região de Coimbra"},
    {"code":"PT","name":"Região de Leiria"},
    {"code":"PT","name":"Viseu Dão Lafões"},
    {"code":"PT","name":"Beira Baixa"},
    {"code":"PT","name":"Médio Tejo"},
    {"code":"PT","name":"Beiras e Serra da Estrela"},
    {"code":"PT","name":"Área Metropolitana de Lisboa"},
    {"code":"PT","name":"Área Metropolitana de Lisboa"},
    {"code":"PT","name":"Alentejo"},
    {"code":"PT","name":"Alentejo Litoral"},
    {"code":"PT","name":"Baixo Alentejo"},
    {"code":"PT","name":"Lezíria do Tejo"},
    {"code":"PT","name":"Alto Alentejo"},
    {"code":"PT","name":"Alentejo Central"},
    {"code":"PT","name":"Região Autónoma dos Açores"},
    {"code":"PT","name":"Região Autónoma dos Açores"},
    {"code":"PT","name":"Região Autónoma dos Açores"},
    {"code":"PT","name":"Região Autónoma da Madeira"},
    {"code":"PT","name":"Região Autónoma da Madeira"},
    {"code":"PT","name":"Região Autónoma da Madeira"},
    {"code":"RO","name":"România"},
    {"code":"RO","name":"Macroregiunea Unu"},
    {"code":"RO","name":"Nord-Vest"},
    {"code":"RO","name":"Bihor"},
    {"code":"RO","name":"Bistriţa-Năsăud"},
    {"code":"RO","name":"Cluj"},
    {"code":"RO","name":"Maramureş"},
    {"code":"RO","name":"Satu Mare"},
    {"code":"RO","name":"Sălaj"},
    {"code":"RO","name":"Centru"},
    {"code":"RO","name":"Alba"},
    {"code":"RO","name":"Braşov"},
    {"code":"RO","name":"Covasna"},
    {"code":"RO","name":"Harghita"},
    {"code":"RO","name":"Mureş"},
    {"code":"RO","name":"Sibiu"},
    {"code":"RO","name":"Macroregiunea Doi"},
    {"code":"RO","name":"Nord-Est"},
    {"code":"RO","name":"Bacău"},
    {"code":"RO","name":"Botoşani"},
    {"code":"RO","name":"Iaşi"},
    {"code":"RO","name":"Neamţ"},
    {"code":"RO","name":"Suceava"},
    {"code":"RO","name":"Vaslui"},
    {"code":"RO","name":"Sud-Est"},
    {"code":"RO","name":"Brăila"},
    {"code":"RO","name":"Buzău"},
    {"code":"RO","name":"Constanţa"},
    {"code":"RO","name":"Galaţi"},
    {"code":"RO","name":"Tulcea"},
    {"code":"RO","name":"Vrancea"},
    {"code":"RO","name":"Macroregiunea Trei"},
    {"code":"RO","name":"Sud-Muntenia"},
    {"code":"RO","name":"Argeş"},
    {"code":"RO","name":"Călăraşi"},
    {"code":"RO","name":"Dâmboviţa"},
    {"code":"RO","name":"Giurgiu"},
    {"code":"RO","name":"Ialomiţa"},
    {"code":"RO","name":"Prahova"},
    {"code":"RO","name":"Teleorman"},
    {"code":"RO","name":"Bucureşti-Ilfov"},
    {"code":"RO","name":"Bucureşti"},
    {"code":"RO","name":"Ilfov"},
    {"code":"RO","name":"Macroregiunea Patru"},
    {"code":"RO","name":"Sud-Vest Oltenia"},
    {"code":"RO","name":"Dolj"},
    {"code":"RO","name":"Gorj"},
    {"code":"RO","name":"Mehedinţi"},
    {"code":"RO","name":"Olt"},
    {"code":"RO","name":"Vâlcea"},
    {"code":"RO","name":"Vest"},
    {"code":"RO","name":"Arad"},
    {"code":"RO","name":"Caraş-Severin"},
    {"code":"RO","name":"Hunedoara"},
    {"code":"RO","name":"Timiş"},
    {"code":"RS","name":"Serbia"},
    {"code":"RS","name":"Serbia - sever"},
    {"code":"RS","name":"City of Belgrade"},
    {"code":"RS","name":"City of Belgrade"},
    {"code":"RS","name":"Autonomous Province of Vojvodina"},
    {"code":"RS","name":"Zapadnobačka oblast"},
    {"code":"RS","name":"Južnobanatska oblast"},
    {"code":"RS","name":"Južnobačka oblast"},
    {"code":"RS","name":"Severnobanatska oblast"},
    {"code":"RS","name":"Severnobačka oblast"},
    {"code":"RS","name":"Srednjobanatska oblast"},
    {"code":"RS","name":"Sremska oblast"},
    {"code":"RS","name":"Serbia - jug"},
    {"code":"RS","name":"Region Šumadije i Zapadne Srbije"},
    {"code":"RS","name":"Zlatiborska oblast"},
    {"code":"RS","name":"Kolubarska oblast"},
    {"code":"RS","name":"Mačvanska oblast"},
    {"code":"RS","name":"Moravička oblast"},
    {"code":"RS","name":"Pomoravska oblast"},
    {"code":"RS","name":"Rasinska oblast"},
    {"code":"RS","name":"Raška oblast"},
    {"code":"RS","name":"Šumadijska oblast"},
    {"code":"UK","name":"Leicestershire, Rutland and Northamptonshire"},
    {"code":"UK","name":"Leicester"},
    {"code":"UK","name":"Leicestershire CC and Rutland"},
    {"code":"UK","name":"West Northamptonshire"},
    {"code":"UK","name":"North Northamptonshire"},
    {"code":"UK","name":"Lincolnshire"},
    {"code":"UK","name":"Lincolnshire"},
    {"code":"UK","name":"West Midlands (England)"},
    {"code":"UK","name":"Herefordshire, Worcestershire and Warwickshire"},
    {"code":"UK","name":"Herefordshire, County of"},
    {"code":"UK","name":"Worcestershire"},
    {"code":"UK","name":"Warwickshire"},
    {"code":"UK","name":"Shropshire and Staffordshire"},
    {"code":"UK","name":"Telford and Wrekin"},
    {"code":"UK","name":"Shropshire CC"},
    {"code":"UK","name":"Stoke-on-Trent"},
    {"code":"UK","name":"Staffordshire CC"},
    {"code":"UK","name":"West Midlands"},
    {"code":"UK","name":"Birmingham"},
    {"code":"UK","name":"Solihull"},
    {"code":"UK","name":"Coventry"},
    {"code":"UK","name":"Dudley"},
    {"code":"UK","name":"Sandwell"},
    {"code":"UK","name":"Walsall"},
    {"code":"UK","name":"Wolverhampton"},
    {"code":"UK","name":"East of England"},
    {"code":"UK","name":"East Anglia"},
    {"code":"UK","name":"Peterborough"},
    {"code":"UK","name":"Cambridgeshire CC"},
    {"code":"UK","name":"Suffolk"},
    {"code":"UK","name":"Norwich and East Norfolk"},
    {"code":"UK","name":"North and West Norfolk"},
    {"code":"UK","name":"Breckland and South Norfolk"},
    {"code":"UK","name":"Bedfordshire and Hertfordshire"},
    {"code":"UK","name":"Luton"},
    {"code":"UK","name":"Hertfordshire"},
    {"code":"UK","name":"Bedford"},
    {"code":"UK","name":"Central Bedfordshire"},
    {"code":"UK","name":"Essex"},
    {"code":"UK","name":"Southend-on-Sea"},
    {"code":"UK","name":"Thurrock"},
    {"code":"UK","name":"Essex Haven Gateway"},
    {"code":"UK","name":"West Essex"},
    {"code":"UK","name":"Heart of Essex"},
    {"code":"UK","name":"Essex Thames Gateway"},
    {"code":"UK","name":"London"},
    {"code":"UK","name":"Inner London — West"},
    {"code":"UK","name":"Camden and City of London"},
    {"code":"UK","name":"Westminster"},
    {"code":"UK","name":"Kensington & Chelsea and Hammersmith & Fulham"},
    {"code":"UK","name":"Wandsworth"},
    {"code":"UK","name":"Inner London — East"},
    {"code":"UK","name":"Hackney and Newham"},
    {"code":"UK","name":"Tower Hamlets"},
    {"code":"UK","name":"Haringey and Islington"},
    {"code":"UK","name":"Lewisham and Southwark"},
    {"code":"UK","name":"Lambeth"},
    {"code":"UK","name":"Outer London — East and North East"},
    {"code":"UK","name":"Bexley and Greenwich"},
    {"code":"UK","name":"Barking & Dagenham and Havering"},
    {"code":"UK","name":"Redbridge and Waltham Forest"},
    {"code":"UK","name":"Enfield"},
    {"code":"UK","name":"Outer London — South"},
    {"code":"UK","name":"Bromley"},
    {"code":"UK","name":"Croydon"},
    {"code":"UK","name":"Merton, Kingston upon Thames and Sutton"},
    {"code":"UK","name":"Outer London — West and North West"},
    {"code":"UK","name":"Barnet"},
    {"code":"UK","name":"Brent"},
    {"code":"UK","name":"Ealing"},
    {"code":"UK","name":"Harrow and Hillingdon"},
    {"code":"UK","name":"Hounslow and Richmond upon Thames"},
    {"code":"UK","name":"South East (England)"},
    {"code":"UK","name":"Berkshire, Buckinghamshire and Oxfordshire"},
    {"code":"UK","name":"Berkshire"},
    {"code":"UK","name":"Milton Keynes"},
    {"code":"UK","name":"Buckinghamshire CC"},
    {"code":"UK","name":"Oxfordshire"},
    {"code":"UK","name":"Surrey, East and West Sussex"},
    {"code":"UK","name":"Brighton and Hove"},
    {"code":"UK","name":"East Sussex CC"},
    {"code":"UK","name":"West Surrey"},
    {"code":"UK","name":"East Surrey"},
    {"code":"UK","name":"West Sussex (South West)"},
    {"code":"UK","name":"West Sussex (North East)"},
    {"code":"UK","name":"Hampshire and Isle of Wight"},
    {"code":"UK","name":"Portsmouth"},
    {"code":"UK","name":"Southampton"},
    {"code":"UK","name":"Isle of Wight"},
    {"code":"UK","name":"South Hampshire"},
    {"code":"UK","name":"Central Hampshire"},
    {"code":"UK","name":"North Hampshire"},
    {"code":"UK","name":"Kent"},
    {"code":"UK","name":"Medway"},
    {"code":"UK","name":"Kent Thames Gateway"},
    {"code":"UK","name":"East Kent"},
    {"code":"UK","name":"Mid Kent"},
    {"code":"UK","name":"West Kent"},
    {"code":"UK","name":"South West (England)"},
    {"code":"UK","name":"Gloucestershire, Wiltshire and Bristol/Bath area"},
    {"code":"UK","name":"Bristol, City of"},
    {"code":"UK","name":"Bath and North East Somerset, North Somerset and South Gloucestershire"},
    {"code":"UK","name":"Gloucestershire"},
    {"code":"UK","name":"Swindon"},
    {"code":"UK","name":"Wiltshire CC"},
    {"code":"UK","name":"Dorset and Somerset"},
    {"code":"UK","name":"Somerset"},
    {"code":"UK","name":"Bournemouth, Christchurch and Poole"},
    {"code":"UK","name":"Dorset"},
    {"code":"UK","name":"Cornwall and Isles of Scilly"},
    {"code":"UK","name":"Cornwall and Isles of Scilly"},
    {"code":"UK","name":"Devon"},
    {"code":"UK","name":"Plymouth"},
    {"code":"UK","name":"Torbay"},
    {"code":"UK","name":"Devon CC"},
    {"code":"UK","name":"Wales"},
    {"code":"UK","name":"West Wales and The Valleys"},
    {"code":"UK","name":"Isle of Anglesey"},
    {"code":"UK","name":"Gwynedd"},
    {"code":"UK","name":"Conwy and Denbighshire"},
    {"code":"UK","name":"South West Wales"},
    {"code":"UK","name":"Central Valleys"},
    {"code":"UK","name":"Gwent Valleys"},
    {"code":"UK","name":"Bridgend and Neath Port Talbot"},
    {"code":"UK","name":"Swansea"},
    {"code":"UK","name":"East Wales"},
    {"code":"UK","name":"Monmouthshire and Newport"},
    {"code":"UK","name":"Cardiff and Vale of Glamorgan"},
    {"code":"UK","name":"Flintshire and Wrexham"},
    {"code":"UK","name":"Powys"},
    {"code":"UK","name":"Scotland"},
    {"code":"UK","name":"North Eastern Scotland"},
    {"code":"UK","name":"Aberdeen City and Aberdeenshire"},
    {"code":"UK","name":"Highlands and Islands"},
    {"code":"UK","name":"Caithness & Sutherland and Ross & Cromarty"},
    {"code":"UK","name":"Inverness & Nairn and Moray, Badenoch & Strathspey"},
    {"code":"UK","name":"Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute"},
    {"code":"UK","name":"Na h-Eileanan Siar (Western Isles)"},
    {"code":"UK","name":"Orkney Islands"},
    {"code":"UK","name":"Shetland Islands"},
    {"code":"UK","name":"Eastern Scotland"},
    {"code":"UK","name":"Angus and Dundee City"},
    {"code":"UK","name":"Clackmannanshire and Fife"},
    {"code":"UK","name":"East Lothian and Midlothian"},
    {"code":"UK","name":"Edinburgh, City of"},
    {"code":"UK","name":"Falkirk"},
    {"code":"UK","name":"Perth & Kinross and Stirling"},
    {"code":"UK","name":"West Lothian"},
    {"code":"UK","name":"West Central Scotland"},
    {"code":"UK","name":"East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond"},
    {"code":"UK","name":"Glasgow City"},
    {"code":"UK","name":"Inverclyde, East Renfrewshire and Renfrewshire"},
    {"code":"UK","name":"North Lanarkshire"},
    {"code":"UK","name":"Southern Scotland"},
    {"code":"UK","name":"Scottish Borders"},
    {"code":"UK","name":"Dumfries & Galloway"},
    {"code":"UK","name":"East Ayrshire and North Ayrshire mainland"},
    {"code":"UK","name":"South Ayrshire"},
    {"code":"UK","name":"South Lanarkshire"},
    {"code":"UK","name":"Northern Ireland"},
    {"code":"UK","name":"Northern Ireland"},
    {"code":"UK","name":"Belfast"},
    {"code":"UK","name":"Armagh City, Banbridge and Craigavon"},
    {"code":"UK","name":"Newry, Mourne and Down"},
    {"code":"UK","name":"Ards and North Down"},
    {"code":"UK","name":"Derry City and Strabane"},
    {"code":"UK","name":"Mid Ulster"},
    {"code":"UK","name":"Causeway Coast and Glens"},
    {"code":"UK","name":"Antrim and Newtownabbey"},
    {"code":"UK","name":"Lisburn and Castlereagh"},
    {"code":"UK","name":"Mid and East Antrim"},
    {"code":"UK","name":"Fermanagh and Omagh"},
    {"code":"NO","name":"Jan Mayen\r\n   \r\n"},
    {"code":"NO","name":"Svalbard"},
    {"code":"NO","name":"Jan Mayen and Svalbard\r\n   \r\n"},
    {"code":"TR","name":"Nevşehir"},
    {"code":"TR","name":"Kırşehir"},
    {"code":"TR","name":"Kayseri, Sivas, Yozgat"},
    {"code":"TR","name":"Kayseri"},
    {"code":"TR","name":"Sivas"},
    {"code":"TR","name":"Yozgat"},
    {"code":"TR","name":"Batı Karadeniz"},
    {"code":"TR","name":"Zonguldak, Karabük, Bartın"},
    {"code":"TR","name":"Zonguldak"},
    {"code":"TR","name":"Karabük"},
    {"code":"TR","name":"Bartın"},
    {"code":"TR","name":"Kastamonu, Çankırı, Sinop"},
    {"code":"TR","name":"Kastamonu"},
    {"code":"TR","name":"Çankırı"},
    {"code":"TR","name":"Sinop"},
    {"code":"TR","name":"Samsun, Tokat, Çorum, Amasya"},
    {"code":"TR","name":"Samsun"},
    {"code":"TR","name":"Tokat"},
    {"code":"TR","name":"Çorum"},
    {"code":"TR","name":"Amasya"},
    {"code":"TR","name":"Doğu Karadeniz"},
    {"code":"TR","name":"Trabzon, Ordu, Giresun, Rize, Artvin, Gümüşhane"},
    {"code":"TR","name":"Trabzon"},
    {"code":"TR","name":"Ordu"},
    {"code":"TR","name":"Giresun"},
    {"code":"TR","name":"Rize"},
    {"code":"TR","name":"Artvin"},
    {"code":"TR","name":"Gümüşhane"},
    {"code":"TR","name":"Kuzeydoğu Anadolu"},
    {"code":"TR","name":"Erzurum, Erzincan, Bayburt"},
    {"code":"TR","name":"Erzurum"},
    {"code":"TR","name":"Erzincan"},
    {"code":"TR","name":"Bayburt"},
    {"code":"TR","name":"Ağrı, Kars, Iğdır, Ardahan"},
    {"code":"TR","name":"Ağrı"},
    {"code":"TR","name":"Kars"},
    {"code":"TR","name":"Iğdır"},
    {"code":"TR","name":"Ardahan"},
    {"code":"TR","name":"Ortadoğu Anadolu"},
    {"code":"TR","name":"Malatya, Elazığ, Bingöl, Tunceli"},
    {"code":"TR","name":"Malatya"},
    {"code":"TR","name":"Elazığ"},
    {"code":"TR","name":"Bingöl"},
    {"code":"TR","name":"Tunceli"},
    {"code":"TR","name":"Van, Muş, Bitlis, Hakkari"},
    {"code":"TR","name":"Van"},
    {"code":"TR","name":"Muş"},
    {"code":"TR","name":"Bitlis"},
    {"code":"TR","name":"Hakkari"},
    {"code":"TR","name":"Güneydoğu Anadolu"},
    {"code":"TR","name":"Gaziantep, Adıyaman, Kilis"},
    {"code":"TR","name":"Gaziantep"},
    {"code":"TR","name":"Adıyaman"},
    {"code":"TR","name":"Kilis"},
    {"code":"TR","name":"Şanlıurfa, Diyarbakır"},
    {"code":"TR","name":"Şanlıurfa"},
    {"code":"TR","name":"Diyarbakır"},
    {"code":"TR","name":"Mardin, Batman, Şırnak, Siirt"},
    {"code":"TR","name":"Mardin"},
    {"code":"TR","name":"Batman"},
    {"code":"TR","name":"Şırnak"},
    {"code":"TR","name":"Siirt"},
    {"code":"UK","name":"United Kingdom"},
    {"code":"UK","name":"North East (England)"},
    {"code":"UK","name":"Tees Valley and Durham"},
    {"code":"UK","name":"Hartlepool and Stockton-on-Tees"},
    {"code":"UK","name":"South Teesside"},
    {"code":"UK","name":"Darlington"},
    {"code":"UK","name":"Durham CC"},
    {"code":"UK","name":"Northumberland and Tyne and Wear"},
    {"code":"UK","name":"Northumberland"},
    {"code":"UK","name":"Tyneside"},
    {"code":"UK","name":"Sunderland"},
    {"code":"UK","name":"North West (England)"},
    {"code":"UK","name":"Cumbria"},
    {"code":"UK","name":"West Cumbria"},
    {"code":"UK","name":"East Cumbria"},
    {"code":"UK","name":"Greater Manchester"},
    {"code":"UK","name":"Manchester"},
    {"code":"UK","name":"Greater Manchester South West"},
    {"code":"UK","name":"Greater Manchester South East"},
    {"code":"UK","name":"Greater Manchester North West"},
    {"code":"UK","name":"Greater Manchester North East"},
    {"code":"UK","name":"Lancashire"},
    {"code":"UK","name":"Blackburn with Darwen"},
    {"code":"UK","name":"Blackpool"},
    {"code":"UK","name":"Lancaster and Wyre"},
    {"code":"UK","name":"Mid Lancashire"},
    {"code":"UK","name":"East Lancashire"},
    {"code":"UK","name":"Chorley and West Lancashire"},
    {"code":"UK","name":"Cheshire"},
    {"code":"UK","name":"Warrington"},
    {"code":"UK","name":"Cheshire East"},
    {"code":"UK","name":"Cheshire West and Chester"},
    {"code":"UK","name":"Merseyside"},
    {"code":"UK","name":"East Merseyside"},
    {"code":"UK","name":"Liverpool"},
    {"code":"UK","name":"Sefton"},
    {"code":"UK","name":"Wirral"},
    {"code":"UK","name":"Yorkshire and the Humber"},
    {"code":"UK","name":"East Yorkshire and Northern Lincolnshire"},
    {"code":"UK","name":"Kingston upon Hull, City of"},
    {"code":"UK","name":"East Riding of Yorkshire"},
    {"code":"UK","name":"North and North East Lincolnshire"},
    {"code":"UK","name":"North Yorkshire"},
    {"code":"UK","name":"York"},
    {"code":"UK","name":"North Yorkshire CC"},
    {"code":"UK","name":"South Yorkshire"},
    {"code":"UK","name":"Barnsley, Doncaster and Rotherham"},
    {"code":"UK","name":"Sheffield"},
    {"code":"UK","name":"West Yorkshire"},
    {"code":"UK","name":"Bradford"},
    {"code":"UK","name":"Leeds"},
    {"code":"UK","name":"Calderdale and Kirklees"},
    {"code":"UK","name":"Wakefield"},
    {"code":"UK","name":"East Midlands (England)"},
    {"code":"UK","name":"Derbyshire and Nottinghamshire"},
    {"code":"UK","name":"Derby"},
    {"code":"UK","name":"East Derbyshire"},
    {"code":"UK","name":"South and West Derbyshire"},
    {"code":"UK","name":"Nottingham"},
    {"code":"UK","name":"North Nottinghamshire"},
    {"code":"UK","name":"South Nottinghamshire"}
];